// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: checkin/v1/checkin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCheckinServiceDoCheckin = "/checkin.v1.CheckinService/DoCheckin"
const OperationCheckinServiceGetCheckinStatus = "/checkin.v1.CheckinService/GetCheckinStatus"

type CheckinServiceHTTPServer interface {
	// DoCheckin POST /api/v1/checkin 每日签到
	DoCheckin(context.Context, *DoCheckinRequest) (*DoCheckinReply, error)
	// GetCheckinStatus GET /api/v1/checkin/status 签到状态与 7 日日历
	GetCheckinStatus(context.Context, *GetCheckinStatusRequest) (*GetCheckinStatusReply, error)
}

func RegisterCheckinServiceHTTPServer(s *http.Server, srv CheckinServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/checkin", _CheckinService_DoCheckin0_HTTP_Handler(srv))
	r.GET("/api/v1/checkin/status", _CheckinService_GetCheckinStatus0_HTTP_Handler(srv))
}

func _CheckinService_DoCheckin0_HTTP_Handler(srv CheckinServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DoCheckinRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinServiceDoCheckin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DoCheckin(ctx, req.(*DoCheckinRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DoCheckinReply)
		return ctx.Result(200, reply)
	}
}

func _CheckinService_GetCheckinStatus0_HTTP_Handler(srv CheckinServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCheckinStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckinServiceGetCheckinStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCheckinStatus(ctx, req.(*GetCheckinStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCheckinStatusReply)
		return ctx.Result(200, reply)
	}
}

type CheckinServiceHTTPClient interface {
	// DoCheckin POST /api/v1/checkin 每日签到
	DoCheckin(ctx context.Context, req *DoCheckinRequest, opts ...http.CallOption) (rsp *DoCheckinReply, err error)
	// GetCheckinStatus GET /api/v1/checkin/status 签到状态与 7 日日历
	GetCheckinStatus(ctx context.Context, req *GetCheckinStatusRequest, opts ...http.CallOption) (rsp *GetCheckinStatusReply, err error)
}

type CheckinServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCheckinServiceHTTPClient(client *http.Client) CheckinServiceHTTPClient {
	return &CheckinServiceHTTPClientImpl{client}
}

// DoCheckin POST /api/v1/checkin 每日签到
func (c *CheckinServiceHTTPClientImpl) DoCheckin(ctx context.Context, in *DoCheckinRequest, opts ...http.CallOption) (*DoCheckinReply, error) {
	var out DoCheckinReply
	pattern := "/api/v1/checkin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCheckinServiceDoCheckin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCheckinStatus GET /api/v1/checkin/status 签到状态与 7 日日历
func (c *CheckinServiceHTTPClientImpl) GetCheckinStatus(ctx context.Context, in *GetCheckinStatusRequest, opts ...http.CallOption) (*GetCheckinStatusReply, error) {
	var out GetCheckinStatusReply
	pattern := "/api/v1/checkin/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCheckinServiceGetCheckinStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
