// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: stats/v1/stats.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStatsServiceGetLeaderboard = "/stats.v1.StatsService/GetLeaderboard"
const OperationStatsServiceListMatches = "/stats.v1.StatsService/ListMatches"

type StatsServiceHTTPServer interface {
	// GetLeaderboard 查询排行榜。
	//
	// HTTP:
	//   GET /api/v1/stats/leaderboard?limit=50
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardReply, error)
	// ListMatches 查询个人历史对局记录（基于当前登录用户）。
	//
	// HTTP:
	//   GET /api/v1/stats/matches?page=1&page_size=20
	ListMatches(context.Context, *ListMatchesRequest) (*ListMatchesReply, error)
}

func RegisterStatsServiceHTTPServer(s *http.Server, srv StatsServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/stats/matches", _StatsService_ListMatches0_HTTP_Handler(srv))
	r.GET("/api/v1/stats/leaderboard", _StatsService_GetLeaderboard0_HTTP_Handler(srv))
}

func _StatsService_ListMatches0_HTTP_Handler(srv StatsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMatchesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStatsServiceListMatches)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMatches(ctx, req.(*ListMatchesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMatchesReply)
		return ctx.Result(200, reply)
	}
}

func _StatsService_GetLeaderboard0_HTTP_Handler(srv StatsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLeaderboardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStatsServiceGetLeaderboard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLeaderboardReply)
		return ctx.Result(200, reply)
	}
}

type StatsServiceHTTPClient interface {
	// GetLeaderboard 查询排行榜。
	//
	// HTTP:
	//   GET /api/v1/stats/leaderboard?limit=50
	GetLeaderboard(ctx context.Context, req *GetLeaderboardRequest, opts ...http.CallOption) (rsp *GetLeaderboardReply, err error)
	// ListMatches 查询个人历史对局记录（基于当前登录用户）。
	//
	// HTTP:
	//   GET /api/v1/stats/matches?page=1&page_size=20
	ListMatches(ctx context.Context, req *ListMatchesRequest, opts ...http.CallOption) (rsp *ListMatchesReply, err error)
}

type StatsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStatsServiceHTTPClient(client *http.Client) StatsServiceHTTPClient {
	return &StatsServiceHTTPClientImpl{client}
}

// GetLeaderboard 查询排行榜。
//
// HTTP:
//   GET /api/v1/stats/leaderboard?limit=50
func (c *StatsServiceHTTPClientImpl) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...http.CallOption) (*GetLeaderboardReply, error) {
	var out GetLeaderboardReply
	pattern := "/api/v1/stats/leaderboard"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStatsServiceGetLeaderboard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMatches 查询个人历史对局记录（基于当前登录用户）。
//
// HTTP:
//   GET /api/v1/stats/matches?page=1&page_size=20
func (c *StatsServiceHTTPClientImpl) ListMatches(ctx context.Context, in *ListMatchesRequest, opts ...http.CallOption) (*ListMatchesReply, error) {
	var out ListMatchesReply
	pattern := "/api/v1/stats/matches"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStatsServiceListMatches))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
