// 萌宠之家（cat-admin）成就模块 API 定义
// 项目文档：docs-all/cat-admin/02-后端开发文档.md
// 成就列表（含当前用户是否已解锁）、成就详情（描述、获得时间）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: achievement/v1/achievement.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Achievement 成就基础信息
type Achievement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl        string                 `protobuf:"bytes,5,opt,name=icon_url,proto3" json:"icon_url,omitempty"`
	ConditionType  string                 `protobuf:"bytes,6,opt,name=condition_type,proto3" json:"condition_type,omitempty"`
	ConditionValue int32                  `protobuf:"varint,7,opt,name=condition_value,proto3" json:"condition_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Achievement) Reset() {
	*x = Achievement{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Achievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Achievement) ProtoMessage() {}

func (x *Achievement) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Achievement.ProtoReflect.Descriptor instead.
func (*Achievement) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{0}
}

func (x *Achievement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Achievement) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Achievement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Achievement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Achievement) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Achievement) GetConditionType() string {
	if x != nil {
		return x.ConditionType
	}
	return ""
}

func (x *Achievement) GetConditionValue() int32 {
	if x != nil {
		return x.ConditionValue
	}
	return 0
}

// AchievementItem 列表项：成就信息 + 是否已解锁及解锁时间
type AchievementItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievement   *Achievement           `protobuf:"bytes,1,opt,name=achievement,proto3" json:"achievement,omitempty"`
	Unlocked      bool                   `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	UnlockedAt    int64                  `protobuf:"varint,3,opt,name=unlocked_at,proto3" json:"unlocked_at,omitempty"` // Unix 秒，未解锁为 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementItem) Reset() {
	*x = AchievementItem{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementItem) ProtoMessage() {}

func (x *AchievementItem) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementItem.ProtoReflect.Descriptor instead.
func (*AchievementItem) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{1}
}

func (x *AchievementItem) GetAchievement() *Achievement {
	if x != nil {
		return x.Achievement
	}
	return nil
}

func (x *AchievementItem) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *AchievementItem) GetUnlockedAt() int64 {
	if x != nil {
		return x.UnlockedAt
	}
	return 0
}

// ListAchievements 成就列表，需登录，返回含当前用户解锁状态
type ListAchievementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAchievementsRequest) Reset() {
	*x = ListAchievementsRequest{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAchievementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAchievementsRequest) ProtoMessage() {}

func (x *ListAchievementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAchievementsRequest.ProtoReflect.Descriptor instead.
func (*ListAchievementsRequest) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{2}
}

type ListAchievementsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AchievementItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAchievementsReply) Reset() {
	*x = ListAchievementsReply{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAchievementsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAchievementsReply) ProtoMessage() {}

func (x *ListAchievementsReply) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAchievementsReply.ProtoReflect.Descriptor instead.
func (*ListAchievementsReply) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{3}
}

func (x *ListAchievementsReply) GetItems() []*AchievementItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetAchievement 成就详情，含获得时间（已解锁时）
type GetAchievementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAchievementRequest) Reset() {
	*x = GetAchievementRequest{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAchievementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAchievementRequest) ProtoMessage() {}

func (x *GetAchievementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAchievementRequest.ProtoReflect.Descriptor instead.
func (*GetAchievementRequest) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{4}
}

func (x *GetAchievementRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAchievementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Achievement   *Achievement           `protobuf:"bytes,1,opt,name=achievement,proto3" json:"achievement,omitempty"`
	Unlocked      bool                   `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	UnlockedAt    int64                  `protobuf:"varint,3,opt,name=unlocked_at,proto3" json:"unlocked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAchievementReply) Reset() {
	*x = GetAchievementReply{}
	mi := &file_achievement_v1_achievement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAchievementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAchievementReply) ProtoMessage() {}

func (x *GetAchievementReply) ProtoReflect() protoreflect.Message {
	mi := &file_achievement_v1_achievement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAchievementReply.ProtoReflect.Descriptor instead.
func (*GetAchievementReply) Descriptor() ([]byte, []int) {
	return file_achievement_v1_achievement_proto_rawDescGZIP(), []int{5}
}

func (x *GetAchievementReply) GetAchievement() *Achievement {
	if x != nil {
		return x.Achievement
	}
	return nil
}

func (x *GetAchievementReply) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *GetAchievementReply) GetUnlockedAt() int64 {
	if x != nil {
		return x.UnlockedAt
	}
	return 0
}

var File_achievement_v1_achievement_proto protoreflect.FileDescriptor

const file_achievement_v1_achievement_proto_rawDesc = "" +
	"\n" +
	" achievement/v1/achievement.proto\x12\x0eachievement.v1\x1a\x1cgoogle/api/annotations.proto\"\xd5\x01\n" +
	"\vAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bicon_url\x18\x05 \x01(\tR\bicon_url\x12&\n" +
	"\x0econdition_type\x18\x06 \x01(\tR\x0econdition_type\x12(\n" +
	"\x0fcondition_value\x18\a \x01(\x05R\x0fcondition_value\"\x8e\x01\n" +
	"\x0fAchievementItem\x12=\n" +
	"\vachievement\x18\x01 \x01(\v2\x1b.achievement.v1.AchievementR\vachievement\x12\x1a\n" +
	"\bunlocked\x18\x02 \x01(\bR\bunlocked\x12 \n" +
	"\vunlocked_at\x18\x03 \x01(\x03R\vunlocked_at\"\x19\n" +
	"\x17ListAchievementsRequest\"N\n" +
	"\x15ListAchievementsReply\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.achievement.v1.AchievementItemR\x05items\"'\n" +
	"\x15GetAchievementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x92\x01\n" +
	"\x13GetAchievementReply\x12=\n" +
	"\vachievement\x18\x01 \x01(\v2\x1b.achievement.v1.AchievementR\vachievement\x12\x1a\n" +
	"\bunlocked\x18\x02 \x01(\bR\bunlocked\x12 \n" +
	"\vunlocked_at\x18\x03 \x01(\x03R\vunlocked_at2\x98\x02\n" +
	"\x12AchievementService\x12\x80\x01\n" +
	"\x10ListAchievements\x12'.achievement.v1.ListAchievementsRequest\x1a%.achievement.v1.ListAchievementsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/achievements\x12\x7f\n" +
	"\x0eGetAchievement\x12%.achievement.v1.GetAchievementRequest\x1a#.achievement.v1.GetAchievementReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/achievements/{id}B!Z\x1frealworld/api/achievement/v1;v1b\x06proto3"

var (
	file_achievement_v1_achievement_proto_rawDescOnce sync.Once
	file_achievement_v1_achievement_proto_rawDescData []byte
)

func file_achievement_v1_achievement_proto_rawDescGZIP() []byte {
	file_achievement_v1_achievement_proto_rawDescOnce.Do(func() {
		file_achievement_v1_achievement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_achievement_v1_achievement_proto_rawDesc), len(file_achievement_v1_achievement_proto_rawDesc)))
	})
	return file_achievement_v1_achievement_proto_rawDescData
}

var file_achievement_v1_achievement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_achievement_v1_achievement_proto_goTypes = []any{
	(*Achievement)(nil),             // 0: achievement.v1.Achievement
	(*AchievementItem)(nil),         // 1: achievement.v1.AchievementItem
	(*ListAchievementsRequest)(nil), // 2: achievement.v1.ListAchievementsRequest
	(*ListAchievementsReply)(nil),   // 3: achievement.v1.ListAchievementsReply
	(*GetAchievementRequest)(nil),   // 4: achievement.v1.GetAchievementRequest
	(*GetAchievementReply)(nil),     // 5: achievement.v1.GetAchievementReply
}
var file_achievement_v1_achievement_proto_depIdxs = []int32{
	0, // 0: achievement.v1.AchievementItem.achievement:type_name -> achievement.v1.Achievement
	1, // 1: achievement.v1.ListAchievementsReply.items:type_name -> achievement.v1.AchievementItem
	0, // 2: achievement.v1.GetAchievementReply.achievement:type_name -> achievement.v1.Achievement
	2, // 3: achievement.v1.AchievementService.ListAchievements:input_type -> achievement.v1.ListAchievementsRequest
	4, // 4: achievement.v1.AchievementService.GetAchievement:input_type -> achievement.v1.GetAchievementRequest
	3, // 5: achievement.v1.AchievementService.ListAchievements:output_type -> achievement.v1.ListAchievementsReply
	5, // 6: achievement.v1.AchievementService.GetAchievement:output_type -> achievement.v1.GetAchievementReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_achievement_v1_achievement_proto_init() }
func file_achievement_v1_achievement_proto_init() {
	if File_achievement_v1_achievement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_achievement_v1_achievement_proto_rawDesc), len(file_achievement_v1_achievement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_achievement_v1_achievement_proto_goTypes,
		DependencyIndexes: file_achievement_v1_achievement_proto_depIdxs,
		MessageInfos:      file_achievement_v1_achievement_proto_msgTypes,
	}.Build()
	File_achievement_v1_achievement_proto = out.File
	file_achievement_v1_achievement_proto_goTypes = nil
	file_achievement_v1_achievement_proto_depIdxs = nil
}
