// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: wechat/v1/wechat.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WechatService_SendGroupText_FullMethodName        = "/wechat.v1.WechatService/SendGroupText"
	WechatService_SendGroupImage_FullMethodName       = "/wechat.v1.WechatService/SendGroupImage"
	WechatService_SendGroupMentionText_FullMethodName = "/wechat.v1.WechatService/SendGroupMentionText"
	WechatService_GetLoginQrcode_FullMethodName       = "/wechat.v1.WechatService/GetLoginQrcode"
	WechatService_GetLoginStatus_FullMethodName       = "/wechat.v1.WechatService/GetLoginStatus"
)

// WechatServiceClient is the client API for WechatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WechatServiceClient interface {
	SendGroupText(ctx context.Context, in *SendGroupTextRequest, opts ...grpc.CallOption) (*SendGroupTextReply, error)
	SendGroupImage(ctx context.Context, in *SendGroupImageRequest, opts ...grpc.CallOption) (*SendGroupImageReply, error)
	SendGroupMentionText(ctx context.Context, in *SendGroupMentionTextRequest, opts ...grpc.CallOption) (*SendGroupMentionTextReply, error)
	GetLoginQrcode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLoginQrcodeReply, error)
	GetLoginStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLoginStatusReply, error)
}

type wechatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWechatServiceClient(cc grpc.ClientConnInterface) WechatServiceClient {
	return &wechatServiceClient{cc}
}

func (c *wechatServiceClient) SendGroupText(ctx context.Context, in *SendGroupTextRequest, opts ...grpc.CallOption) (*SendGroupTextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupTextReply)
	err := c.cc.Invoke(ctx, WechatService_SendGroupText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatServiceClient) SendGroupImage(ctx context.Context, in *SendGroupImageRequest, opts ...grpc.CallOption) (*SendGroupImageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupImageReply)
	err := c.cc.Invoke(ctx, WechatService_SendGroupImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatServiceClient) SendGroupMentionText(ctx context.Context, in *SendGroupMentionTextRequest, opts ...grpc.CallOption) (*SendGroupMentionTextReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupMentionTextReply)
	err := c.cc.Invoke(ctx, WechatService_SendGroupMentionText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatServiceClient) GetLoginQrcode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLoginQrcodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoginQrcodeReply)
	err := c.cc.Invoke(ctx, WechatService_GetLoginQrcode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatServiceClient) GetLoginStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetLoginStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoginStatusReply)
	err := c.cc.Invoke(ctx, WechatService_GetLoginStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WechatServiceServer is the server API for WechatService service.
// All implementations must embed UnimplementedWechatServiceServer
// for forward compatibility.
type WechatServiceServer interface {
	SendGroupText(context.Context, *SendGroupTextRequest) (*SendGroupTextReply, error)
	SendGroupImage(context.Context, *SendGroupImageRequest) (*SendGroupImageReply, error)
	SendGroupMentionText(context.Context, *SendGroupMentionTextRequest) (*SendGroupMentionTextReply, error)
	GetLoginQrcode(context.Context, *emptypb.Empty) (*GetLoginQrcodeReply, error)
	GetLoginStatus(context.Context, *emptypb.Empty) (*GetLoginStatusReply, error)
	mustEmbedUnimplementedWechatServiceServer()
}

// UnimplementedWechatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWechatServiceServer struct{}

func (UnimplementedWechatServiceServer) SendGroupText(context.Context, *SendGroupTextRequest) (*SendGroupTextReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupText not implemented")
}
func (UnimplementedWechatServiceServer) SendGroupImage(context.Context, *SendGroupImageRequest) (*SendGroupImageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupImage not implemented")
}
func (UnimplementedWechatServiceServer) SendGroupMentionText(context.Context, *SendGroupMentionTextRequest) (*SendGroupMentionTextReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupMentionText not implemented")
}
func (UnimplementedWechatServiceServer) GetLoginQrcode(context.Context, *emptypb.Empty) (*GetLoginQrcodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoginQrcode not implemented")
}
func (UnimplementedWechatServiceServer) GetLoginStatus(context.Context, *emptypb.Empty) (*GetLoginStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoginStatus not implemented")
}
func (UnimplementedWechatServiceServer) mustEmbedUnimplementedWechatServiceServer() {}
func (UnimplementedWechatServiceServer) testEmbeddedByValue()                       {}

// UnsafeWechatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WechatServiceServer will
// result in compilation errors.
type UnsafeWechatServiceServer interface {
	mustEmbedUnimplementedWechatServiceServer()
}

func RegisterWechatServiceServer(s grpc.ServiceRegistrar, srv WechatServiceServer) {
	// If the following call panics, it indicates UnimplementedWechatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WechatService_ServiceDesc, srv)
}

func _WechatService_SendGroupText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServiceServer).SendGroupText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WechatService_SendGroupText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServiceServer).SendGroupText(ctx, req.(*SendGroupTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WechatService_SendGroupImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServiceServer).SendGroupImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WechatService_SendGroupImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServiceServer).SendGroupImage(ctx, req.(*SendGroupImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WechatService_SendGroupMentionText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMentionTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServiceServer).SendGroupMentionText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WechatService_SendGroupMentionText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServiceServer).SendGroupMentionText(ctx, req.(*SendGroupMentionTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WechatService_GetLoginQrcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServiceServer).GetLoginQrcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WechatService_GetLoginQrcode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServiceServer).GetLoginQrcode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WechatService_GetLoginStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServiceServer).GetLoginStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WechatService_GetLoginStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServiceServer).GetLoginStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WechatService_ServiceDesc is the grpc.ServiceDesc for WechatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WechatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wechat.v1.WechatService",
	HandlerType: (*WechatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGroupText",
			Handler:    _WechatService_SendGroupText_Handler,
		},
		{
			MethodName: "SendGroupImage",
			Handler:    _WechatService_SendGroupImage_Handler,
		},
		{
			MethodName: "SendGroupMentionText",
			Handler:    _WechatService_SendGroupMentionText_Handler,
		},
		{
			MethodName: "GetLoginQrcode",
			Handler:    _WechatService_GetLoginQrcode_Handler,
		},
		{
			MethodName: "GetLoginStatus",
			Handler:    _WechatService_GetLoginStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wechat/v1/wechat.proto",
}
