// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: wechat/v1/wechat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendGroupTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTopic     string                 `protobuf:"bytes,2,opt,name=room_topic,json=roomTopic,proto3" json:"room_topic,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupTextRequest) Reset() {
	*x = SendGroupTextRequest{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupTextRequest) ProtoMessage() {}

func (x *SendGroupTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupTextRequest.ProtoReflect.Descriptor instead.
func (*SendGroupTextRequest) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{0}
}

func (x *SendGroupTextRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendGroupTextRequest) GetRoomTopic() string {
	if x != nil {
		return x.RoomTopic
	}
	return ""
}

func (x *SendGroupTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendGroupTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupTextReply) Reset() {
	*x = SendGroupTextReply{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupTextReply) ProtoMessage() {}

func (x *SendGroupTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupTextReply.ProtoReflect.Descriptor instead.
func (*SendGroupTextReply) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{1}
}

func (x *SendGroupTextReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendGroupTextReply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendGroupImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTopic     string                 `protobuf:"bytes,2,opt,name=room_topic,json=roomTopic,proto3" json:"room_topic,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ImageBytes    []byte                 `protobuf:"bytes,4,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupImageRequest) Reset() {
	*x = SendGroupImageRequest{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupImageRequest) ProtoMessage() {}

func (x *SendGroupImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupImageRequest.ProtoReflect.Descriptor instead.
func (*SendGroupImageRequest) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{2}
}

func (x *SendGroupImageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendGroupImageRequest) GetRoomTopic() string {
	if x != nil {
		return x.RoomTopic
	}
	return ""
}

func (x *SendGroupImageRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SendGroupImageRequest) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

func (x *SendGroupImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type SendGroupImageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupImageReply) Reset() {
	*x = SendGroupImageReply{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupImageReply) ProtoMessage() {}

func (x *SendGroupImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupImageReply.ProtoReflect.Descriptor instead.
func (*SendGroupImageReply) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{3}
}

func (x *SendGroupImageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendGroupImageReply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendGroupMentionTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomTopic     string                 `protobuf:"bytes,2,opt,name=room_topic,json=roomTopic,proto3" json:"room_topic,omitempty"`
	MentionIds    []string               `protobuf:"bytes,3,rep,name=mention_ids,json=mentionIds,proto3" json:"mention_ids,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMentionTextRequest) Reset() {
	*x = SendGroupMentionTextRequest{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMentionTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMentionTextRequest) ProtoMessage() {}

func (x *SendGroupMentionTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMentionTextRequest.ProtoReflect.Descriptor instead.
func (*SendGroupMentionTextRequest) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{4}
}

func (x *SendGroupMentionTextRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendGroupMentionTextRequest) GetRoomTopic() string {
	if x != nil {
		return x.RoomTopic
	}
	return ""
}

func (x *SendGroupMentionTextRequest) GetMentionIds() []string {
	if x != nil {
		return x.MentionIds
	}
	return nil
}

func (x *SendGroupMentionTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendGroupMentionTextReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMentionTextReply) Reset() {
	*x = SendGroupMentionTextReply{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMentionTextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMentionTextReply) ProtoMessage() {}

func (x *SendGroupMentionTextReply) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMentionTextReply.ProtoReflect.Descriptor instead.
func (*SendGroupMentionTextReply) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{5}
}

func (x *SendGroupMentionTextReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendGroupMentionTextReply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetLoginQrcodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qrcode        string                 `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	QrcodeDataUrl string                 `protobuf:"bytes,2,opt,name=qrcode_data_url,json=qrcodeDataUrl,proto3" json:"qrcode_data_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginQrcodeReply) Reset() {
	*x = GetLoginQrcodeReply{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginQrcodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginQrcodeReply) ProtoMessage() {}

func (x *GetLoginQrcodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginQrcodeReply.ProtoReflect.Descriptor instead.
func (*GetLoginQrcodeReply) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{6}
}

func (x *GetLoginQrcodeReply) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

func (x *GetLoginQrcodeReply) GetQrcodeDataUrl() string {
	if x != nil {
		return x.QrcodeDataUrl
	}
	return ""
}

type GetLoginStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoggedIn      bool                   `protobuf:"varint,1,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	SelfId        string                 `protobuf:"bytes,2,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	SelfName      string                 `protobuf:"bytes,3,opt,name=self_name,json=selfName,proto3" json:"self_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginStatusReply) Reset() {
	*x = GetLoginStatusReply{}
	mi := &file_wechat_v1_wechat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginStatusReply) ProtoMessage() {}

func (x *GetLoginStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_wechat_v1_wechat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginStatusReply.ProtoReflect.Descriptor instead.
func (*GetLoginStatusReply) Descriptor() ([]byte, []int) {
	return file_wechat_v1_wechat_proto_rawDescGZIP(), []int{7}
}

func (x *GetLoginStatusReply) GetLoggedIn() bool {
	if x != nil {
		return x.LoggedIn
	}
	return false
}

func (x *GetLoginStatusReply) GetSelfId() string {
	if x != nil {
		return x.SelfId
	}
	return ""
}

func (x *GetLoginStatusReply) GetSelfName() string {
	if x != nil {
		return x.SelfName
	}
	return ""
}

var File_wechat_v1_wechat_proto protoreflect.FileDescriptor

const file_wechat_v1_wechat_proto_rawDesc = "" +
	"\n" +
	"\x16wechat/v1/wechat.proto\x12\twechat.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"b\n" +
	"\x14SendGroupTextRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"room_topic\x18\x02 \x01(\tR\troomTopic\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"M\n" +
	"\x12SendGroupTextReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\xa9\x01\n" +
	"\x15SendGroupImageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"room_topic\x18\x02 \x01(\tR\troomTopic\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vimage_bytes\x18\x04 \x01(\fR\n" +
	"imageBytes\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"N\n" +
	"\x13SendGroupImageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"\x8a\x01\n" +
	"\x1bSendGroupMentionTextRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"room_topic\x18\x02 \x01(\tR\troomTopic\x12\x1f\n" +
	"\vmention_ids\x18\x03 \x03(\tR\n" +
	"mentionIds\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"T\n" +
	"\x19SendGroupMentionTextReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"U\n" +
	"\x13GetLoginQrcodeReply\x12\x16\n" +
	"\x06qrcode\x18\x01 \x01(\tR\x06qrcode\x12&\n" +
	"\x0fqrcode_data_url\x18\x02 \x01(\tR\rqrcodeDataUrl\"h\n" +
	"\x13GetLoginStatusReply\x12\x1b\n" +
	"\tlogged_in\x18\x01 \x01(\bR\bloggedIn\x12\x17\n" +
	"\aself_id\x18\x02 \x01(\tR\x06selfId\x12\x1b\n" +
	"\tself_name\x18\x03 \x01(\tR\bselfName2\xef\x04\n" +
	"\rWechatService\x12u\n" +
	"\rSendGroupText\x12\x1f.wechat.v1.SendGroupTextRequest\x1a\x1d.wechat.v1.SendGroupTextReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/wechat/v1/group/text\x12y\n" +
	"\x0eSendGroupImage\x12 .wechat.v1.SendGroupImageRequest\x1a\x1e.wechat.v1.SendGroupImageReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/wechat/v1/group/image\x12\x8d\x01\n" +
	"\x14SendGroupMentionText\x12&.wechat.v1.SendGroupMentionTextRequest\x1a$.wechat.v1.SendGroupMentionTextReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/wechat/v1/group/mention\x12m\n" +
	"\x0eGetLoginQrcode\x12\x16.google.protobuf.Empty\x1a\x1e.wechat.v1.GetLoginQrcodeReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/wechat/v1/login/qrcode\x12m\n" +
	"\x0eGetLoginStatus\x12\x16.google.protobuf.Empty\x1a\x1e.wechat.v1.GetLoginStatusReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/wechat/v1/login/statusB\x1cZ\x1arealworld/api/wechat/v1;v1b\x06proto3"

var (
	file_wechat_v1_wechat_proto_rawDescOnce sync.Once
	file_wechat_v1_wechat_proto_rawDescData []byte
)

func file_wechat_v1_wechat_proto_rawDescGZIP() []byte {
	file_wechat_v1_wechat_proto_rawDescOnce.Do(func() {
		file_wechat_v1_wechat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wechat_v1_wechat_proto_rawDesc), len(file_wechat_v1_wechat_proto_rawDesc)))
	})
	return file_wechat_v1_wechat_proto_rawDescData
}

var file_wechat_v1_wechat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wechat_v1_wechat_proto_goTypes = []any{
	(*SendGroupTextRequest)(nil),        // 0: wechat.v1.SendGroupTextRequest
	(*SendGroupTextReply)(nil),          // 1: wechat.v1.SendGroupTextReply
	(*SendGroupImageRequest)(nil),       // 2: wechat.v1.SendGroupImageRequest
	(*SendGroupImageReply)(nil),         // 3: wechat.v1.SendGroupImageReply
	(*SendGroupMentionTextRequest)(nil), // 4: wechat.v1.SendGroupMentionTextRequest
	(*SendGroupMentionTextReply)(nil),   // 5: wechat.v1.SendGroupMentionTextReply
	(*GetLoginQrcodeReply)(nil),         // 6: wechat.v1.GetLoginQrcodeReply
	(*GetLoginStatusReply)(nil),         // 7: wechat.v1.GetLoginStatusReply
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_wechat_v1_wechat_proto_depIdxs = []int32{
	0, // 0: wechat.v1.WechatService.SendGroupText:input_type -> wechat.v1.SendGroupTextRequest
	2, // 1: wechat.v1.WechatService.SendGroupImage:input_type -> wechat.v1.SendGroupImageRequest
	4, // 2: wechat.v1.WechatService.SendGroupMentionText:input_type -> wechat.v1.SendGroupMentionTextRequest
	8, // 3: wechat.v1.WechatService.GetLoginQrcode:input_type -> google.protobuf.Empty
	8, // 4: wechat.v1.WechatService.GetLoginStatus:input_type -> google.protobuf.Empty
	1, // 5: wechat.v1.WechatService.SendGroupText:output_type -> wechat.v1.SendGroupTextReply
	3, // 6: wechat.v1.WechatService.SendGroupImage:output_type -> wechat.v1.SendGroupImageReply
	5, // 7: wechat.v1.WechatService.SendGroupMentionText:output_type -> wechat.v1.SendGroupMentionTextReply
	6, // 8: wechat.v1.WechatService.GetLoginQrcode:output_type -> wechat.v1.GetLoginQrcodeReply
	7, // 9: wechat.v1.WechatService.GetLoginStatus:output_type -> wechat.v1.GetLoginStatusReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wechat_v1_wechat_proto_init() }
func file_wechat_v1_wechat_proto_init() {
	if File_wechat_v1_wechat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wechat_v1_wechat_proto_rawDesc), len(file_wechat_v1_wechat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wechat_v1_wechat_proto_goTypes,
		DependencyIndexes: file_wechat_v1_wechat_proto_depIdxs,
		MessageInfos:      file_wechat_v1_wechat_proto_msgTypes,
	}.Build()
	File_wechat_v1_wechat_proto = out.File
	file_wechat_v1_wechat_proto_goTypes = nil
	file_wechat_v1_wechat_proto_depIdxs = nil
}
