// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld/internal/biz"
	"realworld/internal/conf"
	"realworld/internal/data"
	"realworld/internal/server"
	"realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	realWorldService := service.NewRealWorldService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, logger)
	repository := data.NewArticleRepo(db, logger)
	articleUseCase := biz.NewArticleUseCase(repository)
	articleService := service.NewArticleService(articleUseCase)
	todoRepo := data.NewTodoRepo(dataData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger, articleService, todoService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
