// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld/internal/biz"
	"realworld/internal/conf"
	"realworld/internal/data"
	"realworld/internal/server"
	"realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	realWorldService := service.NewRealWorldService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(userRepo)
	authService := service.NewAuthService(authUsecase, confServer, logger)
	mapRepo := data.NewGameMapRepo(dataData, logger)
	gameSessionRepo := data.NewGameSessionRepo(dataData, logger)
	gameStatsRepo := data.NewGameStatsRepo(dataData, logger)
	gameConfigProvider := data.NewGameConfigProvider(dataData, logger)
	gameUsecase := biz.NewGameUsecase(mapRepo, gameSessionRepo, gameStatsRepo, gameConfigProvider, logger)
	gameService := service.NewGameService(gameUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, gameService, logger)
	repository := data.NewArticleRepo(db, logger)
	articleUseCase := biz.NewArticleUseCase(repository)
	articleService := service.NewArticleService(articleUseCase)
	todoRepo := data.NewTodoRepo(dataData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase, logger)
	statsRepo := data.NewStatsRepo(dataData, logger)
	statsUsecase := biz.NewStatsUsecase(statsRepo, logger)
	statsService := service.NewStatsService(statsUsecase, logger)
	xshProductRepo := data.NewXshProductRepo(dataData, logger)
	xshHotRankRepo := data.NewXshHotRankRepo(dataData, logger)
	xshProductUsecase := biz.NewXshProductUsecase(xshProductRepo, xshHotRankRepo)
	xshProductService := service.NewXshProductService(xshProductUsecase, logger)
	xshTemplateRepo := data.NewXshTemplateRepo(dataData, logger)
	xshDraftRepo := data.NewXshDraftRepo(dataData, logger)
	copyGenerator := biz.NewNoopCopyGenerator()
	coverGenerator := biz.NewNoopCoverGenerator()
	videoProcessor := biz.NewNoopVideoProcessor()
	xshContentUsecase := biz.NewXshContentUsecase(xshTemplateRepo, xshDraftRepo, xshProductRepo, copyGenerator, coverGenerator, videoProcessor)
	xshContentService := service.NewXshContentService(xshContentUsecase, logger)
	xshPlatformAccountRepo := data.NewXshPlatformAccountRepo(dataData, logger)
	xshPublishTaskRepo := data.NewXshPublishTaskRepo(dataData, logger)
	xshScheduleRepo := data.NewXshScheduleRepo(dataData, logger)
	xshDispatchUsecase := biz.NewXshDispatchUsecase(xshPlatformAccountRepo, xshPublishTaskRepo, xshScheduleRepo, xshDraftRepo)
	xshDispatchService := service.NewXshDispatchService(xshDispatchUsecase, logger)
	xshCommentRepo := data.NewXshCommentRepo(dataData, logger)
	xshInboxActionRepo := data.NewXshInboxActionRepo(dataData, logger)
	xshInboxUsecase := biz.NewXshInboxUsecase(xshCommentRepo, xshInboxActionRepo)
	xshInboxService := service.NewXshInboxService(xshInboxUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger, authService, articleService, todoService, gameService, statsService, xshProductService, xshContentService, xshDispatchService, xshInboxService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
