// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld/internal/biz"
	"realworld/internal/conf"
	"realworld/internal/data"
	"realworld/internal/server"
	"realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	realWorldService := service.NewRealWorldService(greeterUsecase)
	mapRepo := data.NewGameMapRepo(dataData, logger)
	gameSessionRepo := data.NewGameSessionRepo(dataData, logger)
	gameStatsRepo := data.NewGameStatsRepo(dataData, logger)
	gameConfigProvider := data.NewGameConfigProvider(dataData, logger)
	gameUsecase := biz.NewGameUsecase(mapRepo, gameSessionRepo, gameStatsRepo, gameConfigProvider, logger)
	gameService := service.NewGameService(gameUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, gameService, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(userRepo)
	authService := service.NewAuthService(authUsecase, confServer, logger)
	repository := data.NewArticleRepo(db, logger)
	articleUseCase := biz.NewArticleUseCase(repository)
	articleService := service.NewArticleService(articleUseCase)
	todoRepo := data.NewTodoRepo(dataData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase, logger)
	statsRepo := data.NewStatsRepo(dataData, logger)
	statsUsecase := biz.NewStatsUsecase(statsRepo, logger)
	statsService := service.NewStatsService(statsUsecase, logger)
	petRepo := data.NewPetRepo(dataData, logger)
	achievementRepo := data.NewAchievementRepo(dataData, logger)
	achievementUnlocker := biz.NewAchievementUnlocker(achievementRepo)
	petUsecase := biz.NewPetUsecase(petRepo, achievementUnlocker, logger)
	appearanceRepo := data.NewAppearanceRepo(dataData, logger)
	appearanceUsecase := biz.NewAppearanceUsecase(appearanceRepo, petRepo, logger)
	petService := service.NewPetService(petUsecase, appearanceUsecase, logger)
	checkinRepo := data.NewCheckinRepo(dataData, logger)
	checkinUsecase := biz.NewCheckinUsecase(checkinRepo, userRepo, achievementUnlocker, logger)
	checkinService := service.NewCheckinService(checkinUsecase, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	shopRepo := data.NewShopRepo(dataData, logger)
	inventoryRepo := data.NewInventoryRepo(dataData, logger)
	shopUsecase := biz.NewShopUsecase(shopRepo, userRepo, inventoryRepo, achievementUnlocker, logger)
	shopService := service.NewShopService(shopUsecase, logger)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, petRepo, logger)
	inventoryService := service.NewInventoryService(inventoryUsecase, logger)
	breedRepo := data.NewBreedRepo(dataData, logger)
	breedUsecase := biz.NewBreedUsecase(breedRepo, logger)
	breedService := service.NewBreedService(breedUsecase, logger)
	achievementUsecase := biz.NewAchievementUsecase(achievementRepo, logger)
	achievementService := service.NewAchievementService(achievementUsecase, logger)
	friendRepo := data.NewFriendRepo(dataData, logger)
	friendRequestRepo := data.NewFriendRequestRepo(dataData, logger)
	friendUsecase := biz.NewFriendUsecase(friendRepo, friendRequestRepo, userRepo, logger)
	friendService := service.NewFriendService(friendUsecase, userRepo, logger)
	xshProductRepo := data.NewXshProductRepo(dataData, logger)
	xshHotRankRepo := data.NewXshHotRankRepo(dataData, logger)
	xshProductUsecase := biz.NewXshProductUsecase(xshProductRepo, xshHotRankRepo)
	xshProductService := service.NewXshProductService(xshProductUsecase, logger)
	xshTemplateRepo := data.NewXshTemplateRepo(dataData, logger)
	xshDraftRepo := data.NewXshDraftRepo(dataData, logger)
	copyGenerator := biz.NewNoopCopyGenerator()
	coverGenerator := biz.NewNoopCoverGenerator()
	videoProcessor := biz.NewNoopVideoProcessor()
	xshContentUsecase := biz.NewXshContentUsecase(xshTemplateRepo, xshDraftRepo, xshProductRepo, copyGenerator, coverGenerator, videoProcessor)
	xshContentService := service.NewXshContentService(xshContentUsecase, logger)
	xshPlatformAccountRepo := data.NewXshPlatformAccountRepo(dataData, logger)
	xshPublishTaskRepo := data.NewXshPublishTaskRepo(dataData, logger)
	xshScheduleRepo := data.NewXshScheduleRepo(dataData, logger)
	xshDispatchUsecase := biz.NewXshDispatchUsecase(xshPlatformAccountRepo, xshPublishTaskRepo, xshScheduleRepo, xshDraftRepo)
	xshDispatchService := service.NewXshDispatchService(xshDispatchUsecase, logger)
	xshCommentRepo := data.NewXshCommentRepo(dataData, logger)
	xshInboxActionRepo := data.NewXshInboxActionRepo(dataData, logger)
	xshInboxUsecase := biz.NewXshInboxUsecase(xshCommentRepo, xshInboxActionRepo)
	xshInboxService := service.NewXshInboxService(xshInboxUsecase, logger)
	wechatGateway := data.NewWechatGateway(logger)
	wechatUsecase := biz.NewWechatUsecase(wechatGateway, logger)
	wechatService := service.NewWechatService(wechatUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger, authService, articleService, todoService, gameService, statsService, petService, checkinService, userService, shopService, inventoryService, breedService, achievementService, friendService, xshProductService, xshContentService, xshDispatchService, xshInboxService, wechatService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
