// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: todo/v1/todo.proto

// Todo 模块的 proto 定义，采用 Kratos 官方推荐的 proto 驱动方式，
// 通过 google.api.http 注解将 gRPC 方法映射为 RESTful HTTP 接口。

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Todo 是待办事项的数据结构定义。
type Todo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 唯一标识，对应数据库中的主键 ID。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 待办事项的具体内容。
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// 是否完成。
	IsCompleted   bool `protobuf:"varint,3,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Todo) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

// GetTodoListReply 是“查询所有待办事项”的返回值结构。
// 为了兼容 JSON 格式，这里返回一个对象，其中 items 字段为数组：
//
//	{
//	  "items": [
//	    { "id": 1, "value": "示例", "isCompleted": false },
//	    ...
//	  ]
//	}
type GetTodoListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Todo                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoListReply) Reset() {
	*x = GetTodoListReply{}
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoListReply) ProtoMessage() {}

func (x *GetTodoListReply) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoListReply.ProtoReflect.Descriptor instead.
func (*GetTodoListReply) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *GetTodoListReply) GetItems() []*Todo {
	if x != nil {
		return x.Items
	}
	return nil
}

// AddTodoRequest 是“添加新的待办事项”的请求体结构。
type AddTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待办事项内容。
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// 是否完成，默认为 false。
	IsCompleted   bool `protobuf:"varint,2,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTodoRequest) Reset() {
	*x = AddTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoRequest) ProtoMessage() {}

func (x *AddTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoRequest.ProtoReflect.Descriptor instead.
func (*AddTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *AddTodoRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AddTodoRequest) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

// TodoReply 是返回单个待办事项的通用结构。
type TodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoReply) Reset() {
	*x = TodoReply{}
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoReply) ProtoMessage() {}

func (x *TodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoReply.ProtoReflect.Descriptor instead.
func (*TodoReply) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *TodoReply) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// UpdateTodoRequest 用于根据 id 更新待办事项状态（取反）。
type UpdateTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待办事项 ID。
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTodoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTodoRequest 用于根据 id 删除待办事项。
type DeleteTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待办事项 ID。
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTodoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTodoReply 表示删除操作的结果状态。
type DeleteTodoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 删除是否成功。
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoReply) Reset() {
	*x = DeleteTodoReply{}
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoReply) ProtoMessage() {}

func (x *DeleteTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoReply.ProtoReflect.Descriptor instead.
func (*DeleteTodoReply) Descriptor() ([]byte, []int) {
	return file_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTodoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_todo_v1_todo_proto protoreflect.FileDescriptor

const file_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x12todo/v1/todo.proto\x12\atodo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\visCompleted\x18\x03 \x01(\bR\visCompleted\"7\n" +
	"\x10GetTodoListReply\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.todo.v1.TodoR\x05items\"H\n" +
	"\x0eAddTodoRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12 \n" +
	"\visCompleted\x18\x02 \x01(\bR\visCompleted\".\n" +
	"\tTodoReply\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"#\n" +
	"\x11UpdateTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"+\n" +
	"\x0fDeleteTodoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfb\x02\n" +
	"\vTodoService\x12W\n" +
	"\vGetTodoList\x12\x16.google.protobuf.Empty\x1a\x19.todo.v1.GetTodoListReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/get-todo\x12P\n" +
	"\aAddTodo\x12\x17.todo.v1.AddTodoRequest\x1a\x12.todo.v1.TodoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/add-todo\x12^\n" +
	"\n" +
	"UpdateTodo\x12\x1a.todo.v1.UpdateTodoRequest\x1a\x12.todo.v1.TodoReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/update-todo/{id}\x12a\n" +
	"\n" +
	"DeleteTodo\x12\x1a.todo.v1.DeleteTodoRequest\x1a\x18.todo.v1.DeleteTodoReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/del-todo/{id}B\x1aZ\x18realworld/api/todo/v1;v1b\x06proto3"

var (
	file_todo_v1_todo_proto_rawDescOnce sync.Once
	file_todo_v1_todo_proto_rawDescData []byte
)

func file_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)))
	})
	return file_todo_v1_todo_proto_rawDescData
}

var file_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_todo_v1_todo_proto_goTypes = []any{
	(*Todo)(nil),              // 0: todo.v1.Todo
	(*GetTodoListReply)(nil),  // 1: todo.v1.GetTodoListReply
	(*AddTodoRequest)(nil),    // 2: todo.v1.AddTodoRequest
	(*TodoReply)(nil),         // 3: todo.v1.TodoReply
	(*UpdateTodoRequest)(nil), // 4: todo.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil), // 5: todo.v1.DeleteTodoRequest
	(*DeleteTodoReply)(nil),   // 6: todo.v1.DeleteTodoReply
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_todo_v1_todo_proto_depIdxs = []int32{
	0, // 0: todo.v1.GetTodoListReply.items:type_name -> todo.v1.Todo
	0, // 1: todo.v1.TodoReply.todo:type_name -> todo.v1.Todo
	7, // 2: todo.v1.TodoService.GetTodoList:input_type -> google.protobuf.Empty
	2, // 3: todo.v1.TodoService.AddTodo:input_type -> todo.v1.AddTodoRequest
	4, // 4: todo.v1.TodoService.UpdateTodo:input_type -> todo.v1.UpdateTodoRequest
	5, // 5: todo.v1.TodoService.DeleteTodo:input_type -> todo.v1.DeleteTodoRequest
	1, // 6: todo.v1.TodoService.GetTodoList:output_type -> todo.v1.GetTodoListReply
	3, // 7: todo.v1.TodoService.AddTodo:output_type -> todo.v1.TodoReply
	3, // 8: todo.v1.TodoService.UpdateTodo:output_type -> todo.v1.TodoReply
	6, // 9: todo.v1.TodoService.DeleteTodo:output_type -> todo.v1.DeleteTodoReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_todo_v1_todo_proto_init() }
func file_todo_v1_todo_proto_init() {
	if File_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_v1_todo_proto_rawDesc), len(file_todo_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_todo_v1_todo_proto_depIdxs,
		MessageInfos:      file_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_todo_v1_todo_proto = out.File
	file_todo_v1_todo_proto_goTypes = nil
	file_todo_v1_todo_proto_depIdxs = nil
}
