// 萌宠之家（cat-admin）商店模块 API 定义
// 项目文档：docs-all/cat-admin/02-后端开发文档.md
// 商品列表、按分类筛选、购买（扣金币并写入背包）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: shop/v1/shop.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShopItem 商品信息，用于列表与购买结果
type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // 食物 / 玩具 / 装扮 等
	PriceCoins    int32                  `protobuf:"varint,4,opt,name=price_coins,proto3" json:"price_coins,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ShopItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ShopItem) GetPriceCoins() int32 {
	if x != nil {
		return x.PriceCoins
	}
	return 0
}

func (x *ShopItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ShopItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListItems 商品列表，可选按 category 筛选
type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // 可选，如 食物、玩具、装扮
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShopItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsReply) Reset() {
	*x = ListItemsReply{}
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsReply) ProtoMessage() {}

func (x *ListItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsReply.ProtoReflect.Descriptor instead.
func (*ListItemsReply) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsReply) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Buy 购买：扣用户金币，将商品写入背包
type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *BuyRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BuyRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyReply) Reset() {
	*x = BuyReply{}
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyReply) ProtoMessage() {}

func (x *BuyReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyReply.ProtoReflect.Descriptor instead.
func (*BuyReply) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

func (x *BuyReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shop_v1_shop_proto protoreflect.FileDescriptor

const file_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/shop.proto\x12\ashop.v1\x1a\x1cgoogle/api/annotations.proto\"\xac\x01\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vprice_coins\x18\x04 \x01(\x05R\vprice_coins\x12\x1c\n" +
	"\timage_url\x18\x05 \x01(\tR\timage_url\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\".\n" +
	"\x10ListItemsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"9\n" +
	"\x0eListItemsReply\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.shop.v1.ShopItemR\x05items\"B\n" +
	"\n" +
	"BuyRequest\x12\x18\n" +
	"\aitem_id\x18\x01 \x01(\x03R\aitem_id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\">\n" +
	"\bBuyReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x01\n" +
	"\vShopService\x12[\n" +
	"\tListItems\x12\x19.shop.v1.ListItemsRequest\x1a\x17.shop.v1.ListItemsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/shop/items\x12J\n" +
	"\x03Buy\x12\x13.shop.v1.BuyRequest\x1a\x11.shop.v1.BuyReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/shop/buyB\x1aZ\x18realworld/api/shop/v1;v1b\x06proto3"

var (
	file_shop_v1_shop_proto_rawDescOnce sync.Once
	file_shop_v1_shop_proto_rawDescData []byte
)

func file_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)))
	})
	return file_shop_v1_shop_proto_rawDescData
}

var file_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shop_v1_shop_proto_goTypes = []any{
	(*ShopItem)(nil),         // 0: shop.v1.ShopItem
	(*ListItemsRequest)(nil), // 1: shop.v1.ListItemsRequest
	(*ListItemsReply)(nil),   // 2: shop.v1.ListItemsReply
	(*BuyRequest)(nil),       // 3: shop.v1.BuyRequest
	(*BuyReply)(nil),         // 4: shop.v1.BuyReply
}
var file_shop_v1_shop_proto_depIdxs = []int32{
	0, // 0: shop.v1.ListItemsReply.items:type_name -> shop.v1.ShopItem
	1, // 1: shop.v1.ShopService.ListItems:input_type -> shop.v1.ListItemsRequest
	3, // 2: shop.v1.ShopService.Buy:input_type -> shop.v1.BuyRequest
	2, // 3: shop.v1.ShopService.ListItems:output_type -> shop.v1.ListItemsReply
	4, // 4: shop.v1.ShopService.Buy:output_type -> shop.v1.BuyReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shop_v1_shop_proto_init() }
func file_shop_v1_shop_proto_init() {
	if File_shop_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_shop_v1_shop_proto_depIdxs,
		MessageInfos:      file_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_shop_v1_shop_proto = out.File
	file_shop_v1_shop_proto_goTypes = nil
	file_shop_v1_shop_proto_depIdxs = nil
}
