// content.proto 定义 AI 内容加工坊（Core）模块的 API。
// 包含：文案模板 CRUD、草稿 CRUD、Gemini 文案生成、封面合成、视频去重。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: xsh/v1/content.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Template 文案模板，对应表 xsh_content_templates。
type Template struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StyleType       string                 `protobuf:"bytes,3,opt,name=style_type,json=styleType,proto3" json:"style_type,omitempty"`
	ContentTemplate string                 `protobuf:"bytes,4,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"`
	SortOrder       int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_xsh_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetStyleType() string {
	if x != nil {
		return x.StyleType
	}
	return ""
}

func (x *Template) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *Template) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Template) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Template) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Draft 内容草稿，对应表 xsh_content_drafts。status: draft | ready | published。
type Draft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TemplateId    uint64                 `protobuf:"varint,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	CopyText      string                 `protobuf:"bytes,4,opt,name=copy_text,json=copyText,proto3" json:"copy_text,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,6,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Draft) Reset() {
	*x = Draft{}
	mi := &file_xsh_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Draft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Draft) ProtoMessage() {}

func (x *Draft) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Draft.ProtoReflect.Descriptor instead.
func (*Draft) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Draft) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Draft) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Draft) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Draft) GetCopyText() string {
	if x != nil {
		return x.CopyText
	}
	return ""
}

func (x *Draft) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Draft) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Draft) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Draft) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Draft) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StyleType     string                 `protobuf:"bytes,1,opt,name=style_type,json=styleType,proto3" json:"style_type,omitempty"` // 可选筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *ListTemplatesRequest) GetStyleType() string {
	if x != nil {
		return x.StyleType
	}
	return ""
}

type ListTemplatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Template            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesReply) Reset() {
	*x = ListTemplatesReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesReply) ProtoMessage() {}

func (x *ListTemplatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesReply.ProtoReflect.Descriptor instead.
func (*ListTemplatesReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *ListTemplatesReply) GetItems() []*Template {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StyleType       string                 `protobuf:"bytes,2,opt,name=style_type,json=styleType,proto3" json:"style_type,omitempty"`
	ContentTemplate string                 `protobuf:"bytes,3,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"`
	SortOrder       int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetStyleType() string {
	if x != nil {
		return x.StyleType
	}
	return ""
}

func (x *CreateTemplateRequest) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *CreateTemplateRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateReply) Reset() {
	*x = CreateTemplateReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateReply) ProtoMessage() {}

func (x *CreateTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateReply.ProtoReflect.Descriptor instead.
func (*CreateTemplateReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTemplateReply) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StyleType       string                 `protobuf:"bytes,3,opt,name=style_type,json=styleType,proto3" json:"style_type,omitempty"`
	ContentTemplate string                 `protobuf:"bytes,4,opt,name=content_template,json=contentTemplate,proto3" json:"content_template,omitempty"`
	SortOrder       int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTemplateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetStyleType() string {
	if x != nil {
		return x.StyleType
	}
	return ""
}

func (x *UpdateTemplateRequest) GetContentTemplate() string {
	if x != nil {
		return x.ContentTemplate
	}
	return ""
}

func (x *UpdateTemplateRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateReply) Reset() {
	*x = UpdateTemplateReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateReply) ProtoMessage() {}

func (x *UpdateTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateReply.ProtoReflect.Descriptor instead.
func (*UpdateTemplateReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateReply) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTemplateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateReply) Reset() {
	*x = DeleteTemplateReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateReply) ProtoMessage() {}

func (x *DeleteTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateReply.ProtoReflect.Descriptor instead.
func (*DeleteTemplateReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTemplateReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TemplateId    uint64                 `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftRequest) Reset() {
	*x = CreateDraftRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftRequest) ProtoMessage() {}

func (x *CreateDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftRequest.ProtoReflect.Descriptor instead.
func (*CreateDraftRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDraftRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateDraftRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type CreateDraftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Draft         *Draft                 `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDraftReply) Reset() {
	*x = CreateDraftReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftReply) ProtoMessage() {}

func (x *CreateDraftReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftReply.ProtoReflect.Descriptor instead.
func (*CreateDraftReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDraftReply) GetDraft() *Draft {
	if x != nil {
		return x.Draft
	}
	return nil
}

type ListDraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProductId     uint64                 `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsRequest) Reset() {
	*x = ListDraftsRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsRequest) ProtoMessage() {}

func (x *ListDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsRequest.ProtoReflect.Descriptor instead.
func (*ListDraftsRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{12}
}

func (x *ListDraftsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDraftsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDraftsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDraftsRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ListDraftsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Draft               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsReply) Reset() {
	*x = ListDraftsReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsReply) ProtoMessage() {}

func (x *ListDraftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsReply.ProtoReflect.Descriptor instead.
func (*ListDraftsReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{13}
}

func (x *ListDraftsReply) GetItems() []*Draft {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDraftsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDraftRequest) Reset() {
	*x = GetDraftRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDraftRequest) ProtoMessage() {}

func (x *GetDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDraftRequest.ProtoReflect.Descriptor instead.
func (*GetDraftRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{14}
}

func (x *GetDraftRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDraftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Draft         *Draft                 `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDraftReply) Reset() {
	*x = GetDraftReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDraftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDraftReply) ProtoMessage() {}

func (x *GetDraftReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDraftReply.ProtoReflect.Descriptor instead.
func (*GetDraftReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetDraftReply) GetDraft() *Draft {
	if x != nil {
		return x.Draft
	}
	return nil
}

type UpdateDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CopyText      string                 `protobuf:"bytes,2,opt,name=copy_text,json=copyText,proto3" json:"copy_text,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDraftRequest) Reset() {
	*x = UpdateDraftRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDraftRequest) ProtoMessage() {}

func (x *UpdateDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDraftRequest.ProtoReflect.Descriptor instead.
func (*UpdateDraftRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDraftRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDraftRequest) GetCopyText() string {
	if x != nil {
		return x.CopyText
	}
	return ""
}

func (x *UpdateDraftRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateDraftRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UpdateDraftRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateDraftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Draft         *Draft                 `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDraftReply) Reset() {
	*x = UpdateDraftReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDraftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDraftReply) ProtoMessage() {}

func (x *UpdateDraftReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDraftReply.ProtoReflect.Descriptor instead.
func (*UpdateDraftReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDraftReply) GetDraft() *Draft {
	if x != nil {
		return x.Draft
	}
	return nil
}

type DeleteDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDraftRequest) Reset() {
	*x = DeleteDraftRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDraftRequest) ProtoMessage() {}

func (x *DeleteDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDraftRequest.ProtoReflect.Descriptor instead.
func (*DeleteDraftRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDraftRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDraftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDraftReply) Reset() {
	*x = DeleteDraftReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDraftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDraftReply) ProtoMessage() {}

func (x *DeleteDraftReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDraftReply.ProtoReflect.Descriptor instead.
func (*DeleteDraftReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDraftReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GenerateCopy 调用 Gemini 3 Flash 按风格生成文案。
type GenerateCopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       uint64                 `protobuf:"varint,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	Style         string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"` // 对应模板 style_type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCopyRequest) Reset() {
	*x = GenerateCopyRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCopyRequest) ProtoMessage() {}

func (x *GenerateCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCopyRequest.ProtoReflect.Descriptor instead.
func (*GenerateCopyRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateCopyRequest) GetDraftId() uint64 {
	if x != nil {
		return x.DraftId
	}
	return 0
}

func (x *GenerateCopyRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type GenerateCopyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CopyText      string                 `protobuf:"bytes,1,opt,name=copy_text,json=copyText,proto3" json:"copy_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCopyReply) Reset() {
	*x = GenerateCopyReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCopyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCopyReply) ProtoMessage() {}

func (x *GenerateCopyReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCopyReply.ProtoReflect.Descriptor instead.
func (*GenerateCopyReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateCopyReply) GetCopyText() string {
	if x != nil {
		return x.CopyText
	}
	return ""
}

type GenerateCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       uint64                 `protobuf:"varint,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCoverRequest) Reset() {
	*x = GenerateCoverRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoverRequest) ProtoMessage() {}

func (x *GenerateCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoverRequest.ProtoReflect.Descriptor instead.
func (*GenerateCoverRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateCoverRequest) GetDraftId() uint64 {
	if x != nil {
		return x.DraftId
	}
	return 0
}

type GenerateCoverReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoverImageUrl string                 `protobuf:"bytes,1,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCoverReply) Reset() {
	*x = GenerateCoverReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCoverReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoverReply) ProtoMessage() {}

func (x *GenerateCoverReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoverReply.ProtoReflect.Descriptor instead.
func (*GenerateCoverReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateCoverReply) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

type ProcessVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       uint64                 `protobuf:"varint,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	Options       string                 `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"` // 抽帧/镜像/滤镜等，可 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVideoRequest) Reset() {
	*x = ProcessVideoRequest{}
	mi := &file_xsh_v1_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoRequest) ProtoMessage() {}

func (x *ProcessVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoRequest.ProtoReflect.Descriptor instead.
func (*ProcessVideoRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{24}
}

func (x *ProcessVideoRequest) GetDraftId() uint64 {
	if x != nil {
		return x.DraftId
	}
	return 0
}

func (x *ProcessVideoRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type ProcessVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVideoReply) Reset() {
	*x = ProcessVideoReply{}
	mi := &file_xsh_v1_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoReply) ProtoMessage() {}

func (x *ProcessVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoReply.ProtoReflect.Descriptor instead.
func (*ProcessVideoReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_content_proto_rawDescGZIP(), []int{25}
}

func (x *ProcessVideoReply) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

var File_xsh_v1_content_proto protoreflect.FileDescriptor

const file_xsh_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x14xsh/v1/content.proto\x12\x06xsh.v1\x1a\x1cgoogle/api/annotations.proto\"\xd5\x01\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"style_type\x18\x03 \x01(\tR\tstyleType\x12)\n" +
	"\x10content_template\x18\x04 \x01(\tR\x0fcontentTemplate\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x8f\x02\n" +
	"\x05Draft\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\x04R\n" +
	"templateId\x12\x1b\n" +
	"\tcopy_text\x18\x04 \x01(\tR\bcopyText\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x06 \x01(\tR\bvideoUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"5\n" +
	"\x14ListTemplatesRequest\x12\x1d\n" +
	"\n" +
	"style_type\x18\x01 \x01(\tR\tstyleType\"<\n" +
	"\x12ListTemplatesReply\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.xsh.v1.TemplateR\x05items\"\x94\x01\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"style_type\x18\x02 \x01(\tR\tstyleType\x12)\n" +
	"\x10content_template\x18\x03 \x01(\tR\x0fcontentTemplate\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"C\n" +
	"\x13CreateTemplateReply\x12,\n" +
	"\btemplate\x18\x01 \x01(\v2\x10.xsh.v1.TemplateR\btemplate\"\xa4\x01\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"style_type\x18\x03 \x01(\tR\tstyleType\x12)\n" +
	"\x10content_template\x18\x04 \x01(\tR\x0fcontentTemplate\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"C\n" +
	"\x13UpdateTemplateReply\x12,\n" +
	"\btemplate\x18\x01 \x01(\v2\x10.xsh.v1.TemplateR\btemplate\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"/\n" +
	"\x13DeleteTemplateReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x12CreateDraftRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x04R\n" +
	"templateId\"7\n" +
	"\x10CreateDraftReply\x12#\n" +
	"\x05draft\x18\x01 \x01(\v2\r.xsh.v1.DraftR\x05draft\"{\n" +
	"\x11ListDraftsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x04R\tproductId\"L\n" +
	"\x0fListDraftsReply\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.xsh.v1.DraftR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"!\n" +
	"\x0fGetDraftRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"4\n" +
	"\rGetDraftReply\x12#\n" +
	"\x05draft\x18\x01 \x01(\v2\r.xsh.v1.DraftR\x05draft\"\x9e\x01\n" +
	"\x12UpdateDraftRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tcopy_text\x18\x02 \x01(\tR\bcopyText\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"7\n" +
	"\x10UpdateDraftReply\x12#\n" +
	"\x05draft\x18\x01 \x01(\v2\r.xsh.v1.DraftR\x05draft\"$\n" +
	"\x12DeleteDraftRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\",\n" +
	"\x10DeleteDraftReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x13GenerateCopyRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\x04R\adraftId\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\"0\n" +
	"\x11GenerateCopyReply\x12\x1b\n" +
	"\tcopy_text\x18\x01 \x01(\tR\bcopyText\"1\n" +
	"\x14GenerateCoverRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\x04R\adraftId\"<\n" +
	"\x12GenerateCoverReply\x12&\n" +
	"\x0fcover_image_url\x18\x01 \x01(\tR\rcoverImageUrl\"J\n" +
	"\x13ProcessVideoRequest\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\x04R\adraftId\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\tR\aoptions\"0\n" +
	"\x11ProcessVideoReply\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl2\xc4\n" +
	"\n" +
	"\x0eContentService\x12h\n" +
	"\rListTemplates\x12\x1c.xsh.v1.ListTemplatesRequest\x1a\x1a.xsh.v1.ListTemplatesReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/xsh/v1/templates\x12n\n" +
	"\x0eCreateTemplate\x12\x1d.xsh.v1.CreateTemplateRequest\x1a\x1b.xsh.v1.CreateTemplateReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/xsh/v1/templates\x12s\n" +
	"\x0eUpdateTemplate\x12\x1d.xsh.v1.UpdateTemplateRequest\x1a\x1b.xsh.v1.UpdateTemplateReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/xsh/v1/templates/{id}\x12p\n" +
	"\x0eDeleteTemplate\x12\x1d.xsh.v1.DeleteTemplateRequest\x1a\x1b.xsh.v1.DeleteTemplateReply\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/xsh/v1/templates/{id}\x12b\n" +
	"\vCreateDraft\x12\x1a.xsh.v1.CreateDraftRequest\x1a\x18.xsh.v1.CreateDraftReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/xsh/v1/drafts\x12\\\n" +
	"\n" +
	"ListDrafts\x12\x19.xsh.v1.ListDraftsRequest\x1a\x17.xsh.v1.ListDraftsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/xsh/v1/drafts\x12[\n" +
	"\bGetDraft\x12\x17.xsh.v1.GetDraftRequest\x1a\x15.xsh.v1.GetDraftReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/xsh/v1/drafts/{id}\x12g\n" +
	"\vUpdateDraft\x12\x1a.xsh.v1.UpdateDraftRequest\x1a\x18.xsh.v1.UpdateDraftReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/xsh/v1/drafts/{id}\x12d\n" +
	"\vDeleteDraft\x12\x1a.xsh.v1.DeleteDraftRequest\x1a\x18.xsh.v1.DeleteDraftReply\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/xsh/v1/drafts/{id}\x12~\n" +
	"\fGenerateCopy\x12\x1b.xsh.v1.GenerateCopyRequest\x1a\x19.xsh.v1.GenerateCopyReply\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/xsh/v1/drafts/{draft_id}/generate-copy\x12\x82\x01\n" +
	"\rGenerateCover\x12\x1c.xsh.v1.GenerateCoverRequest\x1a\x1a.xsh.v1.GenerateCoverReply\"7\x82\xd3\xe4\x93\x021:\x01*\",/api/xsh/v1/drafts/{draft_id}/generate-cover\x12~\n" +
	"\fProcessVideo\x12\x1b.xsh.v1.ProcessVideoRequest\x1a\x19.xsh.v1.ProcessVideoReply\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/xsh/v1/drafts/{draft_id}/process-videoB\x19Z\x17realworld/api/xsh/v1;v1b\x06proto3"

var (
	file_xsh_v1_content_proto_rawDescOnce sync.Once
	file_xsh_v1_content_proto_rawDescData []byte
)

func file_xsh_v1_content_proto_rawDescGZIP() []byte {
	file_xsh_v1_content_proto_rawDescOnce.Do(func() {
		file_xsh_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xsh_v1_content_proto_rawDesc), len(file_xsh_v1_content_proto_rawDesc)))
	})
	return file_xsh_v1_content_proto_rawDescData
}

var file_xsh_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_xsh_v1_content_proto_goTypes = []any{
	(*Template)(nil),              // 0: xsh.v1.Template
	(*Draft)(nil),                 // 1: xsh.v1.Draft
	(*ListTemplatesRequest)(nil),  // 2: xsh.v1.ListTemplatesRequest
	(*ListTemplatesReply)(nil),    // 3: xsh.v1.ListTemplatesReply
	(*CreateTemplateRequest)(nil), // 4: xsh.v1.CreateTemplateRequest
	(*CreateTemplateReply)(nil),   // 5: xsh.v1.CreateTemplateReply
	(*UpdateTemplateRequest)(nil), // 6: xsh.v1.UpdateTemplateRequest
	(*UpdateTemplateReply)(nil),   // 7: xsh.v1.UpdateTemplateReply
	(*DeleteTemplateRequest)(nil), // 8: xsh.v1.DeleteTemplateRequest
	(*DeleteTemplateReply)(nil),   // 9: xsh.v1.DeleteTemplateReply
	(*CreateDraftRequest)(nil),    // 10: xsh.v1.CreateDraftRequest
	(*CreateDraftReply)(nil),      // 11: xsh.v1.CreateDraftReply
	(*ListDraftsRequest)(nil),     // 12: xsh.v1.ListDraftsRequest
	(*ListDraftsReply)(nil),       // 13: xsh.v1.ListDraftsReply
	(*GetDraftRequest)(nil),       // 14: xsh.v1.GetDraftRequest
	(*GetDraftReply)(nil),         // 15: xsh.v1.GetDraftReply
	(*UpdateDraftRequest)(nil),    // 16: xsh.v1.UpdateDraftRequest
	(*UpdateDraftReply)(nil),      // 17: xsh.v1.UpdateDraftReply
	(*DeleteDraftRequest)(nil),    // 18: xsh.v1.DeleteDraftRequest
	(*DeleteDraftReply)(nil),      // 19: xsh.v1.DeleteDraftReply
	(*GenerateCopyRequest)(nil),   // 20: xsh.v1.GenerateCopyRequest
	(*GenerateCopyReply)(nil),     // 21: xsh.v1.GenerateCopyReply
	(*GenerateCoverRequest)(nil),  // 22: xsh.v1.GenerateCoverRequest
	(*GenerateCoverReply)(nil),    // 23: xsh.v1.GenerateCoverReply
	(*ProcessVideoRequest)(nil),   // 24: xsh.v1.ProcessVideoRequest
	(*ProcessVideoReply)(nil),     // 25: xsh.v1.ProcessVideoReply
}
var file_xsh_v1_content_proto_depIdxs = []int32{
	0,  // 0: xsh.v1.ListTemplatesReply.items:type_name -> xsh.v1.Template
	0,  // 1: xsh.v1.CreateTemplateReply.template:type_name -> xsh.v1.Template
	0,  // 2: xsh.v1.UpdateTemplateReply.template:type_name -> xsh.v1.Template
	1,  // 3: xsh.v1.CreateDraftReply.draft:type_name -> xsh.v1.Draft
	1,  // 4: xsh.v1.ListDraftsReply.items:type_name -> xsh.v1.Draft
	1,  // 5: xsh.v1.GetDraftReply.draft:type_name -> xsh.v1.Draft
	1,  // 6: xsh.v1.UpdateDraftReply.draft:type_name -> xsh.v1.Draft
	2,  // 7: xsh.v1.ContentService.ListTemplates:input_type -> xsh.v1.ListTemplatesRequest
	4,  // 8: xsh.v1.ContentService.CreateTemplate:input_type -> xsh.v1.CreateTemplateRequest
	6,  // 9: xsh.v1.ContentService.UpdateTemplate:input_type -> xsh.v1.UpdateTemplateRequest
	8,  // 10: xsh.v1.ContentService.DeleteTemplate:input_type -> xsh.v1.DeleteTemplateRequest
	10, // 11: xsh.v1.ContentService.CreateDraft:input_type -> xsh.v1.CreateDraftRequest
	12, // 12: xsh.v1.ContentService.ListDrafts:input_type -> xsh.v1.ListDraftsRequest
	14, // 13: xsh.v1.ContentService.GetDraft:input_type -> xsh.v1.GetDraftRequest
	16, // 14: xsh.v1.ContentService.UpdateDraft:input_type -> xsh.v1.UpdateDraftRequest
	18, // 15: xsh.v1.ContentService.DeleteDraft:input_type -> xsh.v1.DeleteDraftRequest
	20, // 16: xsh.v1.ContentService.GenerateCopy:input_type -> xsh.v1.GenerateCopyRequest
	22, // 17: xsh.v1.ContentService.GenerateCover:input_type -> xsh.v1.GenerateCoverRequest
	24, // 18: xsh.v1.ContentService.ProcessVideo:input_type -> xsh.v1.ProcessVideoRequest
	3,  // 19: xsh.v1.ContentService.ListTemplates:output_type -> xsh.v1.ListTemplatesReply
	5,  // 20: xsh.v1.ContentService.CreateTemplate:output_type -> xsh.v1.CreateTemplateReply
	7,  // 21: xsh.v1.ContentService.UpdateTemplate:output_type -> xsh.v1.UpdateTemplateReply
	9,  // 22: xsh.v1.ContentService.DeleteTemplate:output_type -> xsh.v1.DeleteTemplateReply
	11, // 23: xsh.v1.ContentService.CreateDraft:output_type -> xsh.v1.CreateDraftReply
	13, // 24: xsh.v1.ContentService.ListDrafts:output_type -> xsh.v1.ListDraftsReply
	15, // 25: xsh.v1.ContentService.GetDraft:output_type -> xsh.v1.GetDraftReply
	17, // 26: xsh.v1.ContentService.UpdateDraft:output_type -> xsh.v1.UpdateDraftReply
	19, // 27: xsh.v1.ContentService.DeleteDraft:output_type -> xsh.v1.DeleteDraftReply
	21, // 28: xsh.v1.ContentService.GenerateCopy:output_type -> xsh.v1.GenerateCopyReply
	23, // 29: xsh.v1.ContentService.GenerateCover:output_type -> xsh.v1.GenerateCoverReply
	25, // 30: xsh.v1.ContentService.ProcessVideo:output_type -> xsh.v1.ProcessVideoReply
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_xsh_v1_content_proto_init() }
func file_xsh_v1_content_proto_init() {
	if File_xsh_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xsh_v1_content_proto_rawDesc), len(file_xsh_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xsh_v1_content_proto_goTypes,
		DependencyIndexes: file_xsh_v1_content_proto_depIdxs,
		MessageInfos:      file_xsh_v1_content_proto_msgTypes,
	}.Build()
	File_xsh_v1_content_proto = out.File
	file_xsh_v1_content_proto_goTypes = nil
	file_xsh_v1_content_proto_depIdxs = nil
}
