// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: xsh/v1/content.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationContentServiceCreateDraft = "/xsh.v1.ContentService/CreateDraft"
const OperationContentServiceCreateTemplate = "/xsh.v1.ContentService/CreateTemplate"
const OperationContentServiceDeleteDraft = "/xsh.v1.ContentService/DeleteDraft"
const OperationContentServiceDeleteTemplate = "/xsh.v1.ContentService/DeleteTemplate"
const OperationContentServiceGenerateCopy = "/xsh.v1.ContentService/GenerateCopy"
const OperationContentServiceGenerateCover = "/xsh.v1.ContentService/GenerateCover"
const OperationContentServiceGetDraft = "/xsh.v1.ContentService/GetDraft"
const OperationContentServiceListDrafts = "/xsh.v1.ContentService/ListDrafts"
const OperationContentServiceListTemplates = "/xsh.v1.ContentService/ListTemplates"
const OperationContentServiceProcessVideo = "/xsh.v1.ContentService/ProcessVideo"
const OperationContentServiceUpdateDraft = "/xsh.v1.ContentService/UpdateDraft"
const OperationContentServiceUpdateTemplate = "/xsh.v1.ContentService/UpdateTemplate"

type ContentServiceHTTPServer interface {
	CreateDraft(context.Context, *CreateDraftRequest) (*CreateDraftReply, error)
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateReply, error)
	DeleteDraft(context.Context, *DeleteDraftRequest) (*DeleteDraftReply, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateReply, error)
	GenerateCopy(context.Context, *GenerateCopyRequest) (*GenerateCopyReply, error)
	GenerateCover(context.Context, *GenerateCoverRequest) (*GenerateCoverReply, error)
	GetDraft(context.Context, *GetDraftRequest) (*GetDraftReply, error)
	ListDrafts(context.Context, *ListDraftsRequest) (*ListDraftsReply, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesReply, error)
	ProcessVideo(context.Context, *ProcessVideoRequest) (*ProcessVideoReply, error)
	UpdateDraft(context.Context, *UpdateDraftRequest) (*UpdateDraftReply, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateReply, error)
}

func RegisterContentServiceHTTPServer(s *http.Server, srv ContentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/xsh/v1/templates", _ContentService_ListTemplates0_HTTP_Handler(srv))
	r.POST("/api/xsh/v1/templates", _ContentService_CreateTemplate0_HTTP_Handler(srv))
	r.PUT("/api/xsh/v1/templates/{id}", _ContentService_UpdateTemplate0_HTTP_Handler(srv))
	r.DELETE("/api/xsh/v1/templates/{id}", _ContentService_DeleteTemplate0_HTTP_Handler(srv))
	r.POST("/api/xsh/v1/drafts", _ContentService_CreateDraft0_HTTP_Handler(srv))
	r.GET("/api/xsh/v1/drafts", _ContentService_ListDrafts0_HTTP_Handler(srv))
	r.GET("/api/xsh/v1/drafts/{id}", _ContentService_GetDraft0_HTTP_Handler(srv))
	r.PUT("/api/xsh/v1/drafts/{id}", _ContentService_UpdateDraft0_HTTP_Handler(srv))
	r.DELETE("/api/xsh/v1/drafts/{id}", _ContentService_DeleteDraft0_HTTP_Handler(srv))
	r.POST("/api/xsh/v1/drafts/{draft_id}/generate-copy", _ContentService_GenerateCopy0_HTTP_Handler(srv))
	r.POST("/api/xsh/v1/drafts/{draft_id}/generate-cover", _ContentService_GenerateCover0_HTTP_Handler(srv))
	r.POST("/api/xsh/v1/drafts/{draft_id}/process-video", _ContentService_ProcessVideo0_HTTP_Handler(srv))
}

func _ContentService_ListTemplates0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceListTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTemplates(ctx, req.(*ListTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTemplatesReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_CreateTemplate0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTemplateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceCreateTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTemplate(ctx, req.(*CreateTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTemplateReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_UpdateTemplate0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTemplateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceUpdateTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTemplateReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_DeleteTemplate0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceDeleteTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTemplateReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_CreateDraft0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDraftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceCreateDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDraft(ctx, req.(*CreateDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDraftReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_ListDrafts0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDraftsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceListDrafts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDrafts(ctx, req.(*ListDraftsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDraftsReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_GetDraft0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDraftRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceGetDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDraft(ctx, req.(*GetDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDraftReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_UpdateDraft0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDraftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceUpdateDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDraft(ctx, req.(*UpdateDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDraftReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_DeleteDraft0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDraftRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceDeleteDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDraft(ctx, req.(*DeleteDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDraftReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_GenerateCopy0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateCopyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceGenerateCopy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateCopy(ctx, req.(*GenerateCopyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateCopyReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_GenerateCover0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateCoverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceGenerateCover)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateCover(ctx, req.(*GenerateCoverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateCoverReply)
		return ctx.Result(200, reply)
	}
}

func _ContentService_ProcessVideo0_HTTP_Handler(srv ContentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProcessVideoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentServiceProcessVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProcessVideo(ctx, req.(*ProcessVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProcessVideoReply)
		return ctx.Result(200, reply)
	}
}

type ContentServiceHTTPClient interface {
	CreateDraft(ctx context.Context, req *CreateDraftRequest, opts ...http.CallOption) (rsp *CreateDraftReply, err error)
	CreateTemplate(ctx context.Context, req *CreateTemplateRequest, opts ...http.CallOption) (rsp *CreateTemplateReply, err error)
	DeleteDraft(ctx context.Context, req *DeleteDraftRequest, opts ...http.CallOption) (rsp *DeleteDraftReply, err error)
	DeleteTemplate(ctx context.Context, req *DeleteTemplateRequest, opts ...http.CallOption) (rsp *DeleteTemplateReply, err error)
	GenerateCopy(ctx context.Context, req *GenerateCopyRequest, opts ...http.CallOption) (rsp *GenerateCopyReply, err error)
	GenerateCover(ctx context.Context, req *GenerateCoverRequest, opts ...http.CallOption) (rsp *GenerateCoverReply, err error)
	GetDraft(ctx context.Context, req *GetDraftRequest, opts ...http.CallOption) (rsp *GetDraftReply, err error)
	ListDrafts(ctx context.Context, req *ListDraftsRequest, opts ...http.CallOption) (rsp *ListDraftsReply, err error)
	ListTemplates(ctx context.Context, req *ListTemplatesRequest, opts ...http.CallOption) (rsp *ListTemplatesReply, err error)
	ProcessVideo(ctx context.Context, req *ProcessVideoRequest, opts ...http.CallOption) (rsp *ProcessVideoReply, err error)
	UpdateDraft(ctx context.Context, req *UpdateDraftRequest, opts ...http.CallOption) (rsp *UpdateDraftReply, err error)
	UpdateTemplate(ctx context.Context, req *UpdateTemplateRequest, opts ...http.CallOption) (rsp *UpdateTemplateReply, err error)
}

type ContentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewContentServiceHTTPClient(client *http.Client) ContentServiceHTTPClient {
	return &ContentServiceHTTPClientImpl{client}
}

func (c *ContentServiceHTTPClientImpl) CreateDraft(ctx context.Context, in *CreateDraftRequest, opts ...http.CallOption) (*CreateDraftReply, error) {
	var out CreateDraftReply
	pattern := "/api/xsh/v1/drafts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceCreateDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...http.CallOption) (*CreateTemplateReply, error) {
	var out CreateTemplateReply
	pattern := "/api/xsh/v1/templates"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceCreateTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...http.CallOption) (*DeleteDraftReply, error) {
	var out DeleteDraftReply
	pattern := "/api/xsh/v1/drafts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentServiceDeleteDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...http.CallOption) (*DeleteTemplateReply, error) {
	var out DeleteTemplateReply
	pattern := "/api/xsh/v1/templates/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentServiceDeleteTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) GenerateCopy(ctx context.Context, in *GenerateCopyRequest, opts ...http.CallOption) (*GenerateCopyReply, error) {
	var out GenerateCopyReply
	pattern := "/api/xsh/v1/drafts/{draft_id}/generate-copy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceGenerateCopy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) GenerateCover(ctx context.Context, in *GenerateCoverRequest, opts ...http.CallOption) (*GenerateCoverReply, error) {
	var out GenerateCoverReply
	pattern := "/api/xsh/v1/drafts/{draft_id}/generate-cover"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceGenerateCover))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) GetDraft(ctx context.Context, in *GetDraftRequest, opts ...http.CallOption) (*GetDraftReply, error) {
	var out GetDraftReply
	pattern := "/api/xsh/v1/drafts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentServiceGetDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...http.CallOption) (*ListDraftsReply, error) {
	var out ListDraftsReply
	pattern := "/api/xsh/v1/drafts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentServiceListDrafts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...http.CallOption) (*ListTemplatesReply, error) {
	var out ListTemplatesReply
	pattern := "/api/xsh/v1/templates"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentServiceListTemplates))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) ProcessVideo(ctx context.Context, in *ProcessVideoRequest, opts ...http.CallOption) (*ProcessVideoReply, error) {
	var out ProcessVideoReply
	pattern := "/api/xsh/v1/drafts/{draft_id}/process-video"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceProcessVideo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...http.CallOption) (*UpdateDraftReply, error) {
	var out UpdateDraftReply
	pattern := "/api/xsh/v1/drafts/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceUpdateDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentServiceHTTPClientImpl) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...http.CallOption) (*UpdateTemplateReply, error) {
	var out UpdateTemplateReply
	pattern := "/api/xsh/v1/templates/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentServiceUpdateTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
