// dispatch.proto 定义多账号分发矩阵（Dispatch）模块的 API。
// 包含：平台账号 CRUD、定时规则、发布任务创建/列表/重试/取消；实际发布由 Playwright-go Worker 消费任务执行。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: xsh/v1/dispatch.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DispatchService_ListPlatformAccounts_FullMethodName = "/xsh.v1.DispatchService/ListPlatformAccounts"
	DispatchService_BindAccount_FullMethodName          = "/xsh.v1.DispatchService/BindAccount"
	DispatchService_UpdateAccount_FullMethodName        = "/xsh.v1.DispatchService/UpdateAccount"
	DispatchService_UnbindAccount_FullMethodName        = "/xsh.v1.DispatchService/UnbindAccount"
	DispatchService_ListSchedules_FullMethodName        = "/xsh.v1.DispatchService/ListSchedules"
	DispatchService_CreateSchedule_FullMethodName       = "/xsh.v1.DispatchService/CreateSchedule"
	DispatchService_UpdateSchedule_FullMethodName       = "/xsh.v1.DispatchService/UpdateSchedule"
	DispatchService_DeleteSchedule_FullMethodName       = "/xsh.v1.DispatchService/DeleteSchedule"
	DispatchService_CreatePublishTask_FullMethodName    = "/xsh.v1.DispatchService/CreatePublishTask"
	DispatchService_ListPublishTasks_FullMethodName     = "/xsh.v1.DispatchService/ListPublishTasks"
	DispatchService_RetryPublishTask_FullMethodName     = "/xsh.v1.DispatchService/RetryPublishTask"
	DispatchService_CancelPublishTask_FullMethodName    = "/xsh.v1.DispatchService/CancelPublishTask"
)

// DispatchServiceClient is the client API for DispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DispatchService 多账号分发矩阵 HTTP/gRPC 服务。
type DispatchServiceClient interface {
	ListPlatformAccounts(ctx context.Context, in *ListPlatformAccountsRequest, opts ...grpc.CallOption) (*ListPlatformAccountsReply, error)
	BindAccount(ctx context.Context, in *BindAccountRequest, opts ...grpc.CallOption) (*BindAccountReply, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountReply, error)
	UnbindAccount(ctx context.Context, in *UnbindAccountRequest, opts ...grpc.CallOption) (*UnbindAccountReply, error)
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesReply, error)
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleReply, error)
	UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleReply, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleReply, error)
	CreatePublishTask(ctx context.Context, in *CreatePublishTaskRequest, opts ...grpc.CallOption) (*CreatePublishTaskReply, error)
	ListPublishTasks(ctx context.Context, in *ListPublishTasksRequest, opts ...grpc.CallOption) (*ListPublishTasksReply, error)
	RetryPublishTask(ctx context.Context, in *RetryPublishTaskRequest, opts ...grpc.CallOption) (*RetryPublishTaskReply, error)
	CancelPublishTask(ctx context.Context, in *CancelPublishTaskRequest, opts ...grpc.CallOption) (*CancelPublishTaskReply, error)
}

type dispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchServiceClient(cc grpc.ClientConnInterface) DispatchServiceClient {
	return &dispatchServiceClient{cc}
}

func (c *dispatchServiceClient) ListPlatformAccounts(ctx context.Context, in *ListPlatformAccountsRequest, opts ...grpc.CallOption) (*ListPlatformAccountsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformAccountsReply)
	err := c.cc.Invoke(ctx, DispatchService_ListPlatformAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) BindAccount(ctx context.Context, in *BindAccountRequest, opts ...grpc.CallOption) (*BindAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindAccountReply)
	err := c.cc.Invoke(ctx, DispatchService_BindAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccountReply)
	err := c.cc.Invoke(ctx, DispatchService_UpdateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) UnbindAccount(ctx context.Context, in *UnbindAccountRequest, opts ...grpc.CallOption) (*UnbindAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindAccountReply)
	err := c.cc.Invoke(ctx, DispatchService_UnbindAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesReply)
	err := c.cc.Invoke(ctx, DispatchService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScheduleReply)
	err := c.cc.Invoke(ctx, DispatchService_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) UpdateSchedule(ctx context.Context, in *UpdateScheduleRequest, opts ...grpc.CallOption) (*UpdateScheduleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScheduleReply)
	err := c.cc.Invoke(ctx, DispatchService_UpdateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScheduleReply)
	err := c.cc.Invoke(ctx, DispatchService_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) CreatePublishTask(ctx context.Context, in *CreatePublishTaskRequest, opts ...grpc.CallOption) (*CreatePublishTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePublishTaskReply)
	err := c.cc.Invoke(ctx, DispatchService_CreatePublishTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) ListPublishTasks(ctx context.Context, in *ListPublishTasksRequest, opts ...grpc.CallOption) (*ListPublishTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishTasksReply)
	err := c.cc.Invoke(ctx, DispatchService_ListPublishTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) RetryPublishTask(ctx context.Context, in *RetryPublishTaskRequest, opts ...grpc.CallOption) (*RetryPublishTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryPublishTaskReply)
	err := c.cc.Invoke(ctx, DispatchService_RetryPublishTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchServiceClient) CancelPublishTask(ctx context.Context, in *CancelPublishTaskRequest, opts ...grpc.CallOption) (*CancelPublishTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPublishTaskReply)
	err := c.cc.Invoke(ctx, DispatchService_CancelPublishTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServiceServer is the server API for DispatchService service.
// All implementations must embed UnimplementedDispatchServiceServer
// for forward compatibility.
//
// DispatchService 多账号分发矩阵 HTTP/gRPC 服务。
type DispatchServiceServer interface {
	ListPlatformAccounts(context.Context, *ListPlatformAccountsRequest) (*ListPlatformAccountsReply, error)
	BindAccount(context.Context, *BindAccountRequest) (*BindAccountReply, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountReply, error)
	UnbindAccount(context.Context, *UnbindAccountRequest) (*UnbindAccountReply, error)
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesReply, error)
	CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleReply, error)
	UpdateSchedule(context.Context, *UpdateScheduleRequest) (*UpdateScheduleReply, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleReply, error)
	CreatePublishTask(context.Context, *CreatePublishTaskRequest) (*CreatePublishTaskReply, error)
	ListPublishTasks(context.Context, *ListPublishTasksRequest) (*ListPublishTasksReply, error)
	RetryPublishTask(context.Context, *RetryPublishTaskRequest) (*RetryPublishTaskReply, error)
	CancelPublishTask(context.Context, *CancelPublishTaskRequest) (*CancelPublishTaskReply, error)
	mustEmbedUnimplementedDispatchServiceServer()
}

// UnimplementedDispatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServiceServer struct{}

func (UnimplementedDispatchServiceServer) ListPlatformAccounts(context.Context, *ListPlatformAccountsRequest) (*ListPlatformAccountsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatformAccounts not implemented")
}
func (UnimplementedDispatchServiceServer) BindAccount(context.Context, *BindAccountRequest) (*BindAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAccount not implemented")
}
func (UnimplementedDispatchServiceServer) UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (UnimplementedDispatchServiceServer) UnbindAccount(context.Context, *UnbindAccountRequest) (*UnbindAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindAccount not implemented")
}
func (UnimplementedDispatchServiceServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedDispatchServiceServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedDispatchServiceServer) UpdateSchedule(context.Context, *UpdateScheduleRequest) (*UpdateScheduleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (UnimplementedDispatchServiceServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedDispatchServiceServer) CreatePublishTask(context.Context, *CreatePublishTaskRequest) (*CreatePublishTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePublishTask not implemented")
}
func (UnimplementedDispatchServiceServer) ListPublishTasks(context.Context, *ListPublishTasksRequest) (*ListPublishTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublishTasks not implemented")
}
func (UnimplementedDispatchServiceServer) RetryPublishTask(context.Context, *RetryPublishTaskRequest) (*RetryPublishTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryPublishTask not implemented")
}
func (UnimplementedDispatchServiceServer) CancelPublishTask(context.Context, *CancelPublishTaskRequest) (*CancelPublishTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPublishTask not implemented")
}
func (UnimplementedDispatchServiceServer) mustEmbedUnimplementedDispatchServiceServer() {}
func (UnimplementedDispatchServiceServer) testEmbeddedByValue()                         {}

// UnsafeDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServiceServer will
// result in compilation errors.
type UnsafeDispatchServiceServer interface {
	mustEmbedUnimplementedDispatchServiceServer()
}

func RegisterDispatchServiceServer(s grpc.ServiceRegistrar, srv DispatchServiceServer) {
	// If the following call panics, it indicates UnimplementedDispatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DispatchService_ServiceDesc, srv)
}

func _DispatchService_ListPlatformAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).ListPlatformAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_ListPlatformAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).ListPlatformAccounts(ctx, req.(*ListPlatformAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_BindAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).BindAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_BindAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).BindAccount(ctx, req.(*BindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_UpdateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_UnbindAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).UnbindAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_UnbindAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).UnbindAccount(ctx, req.(*UnbindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_UpdateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).UpdateSchedule(ctx, req.(*UpdateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_CreatePublishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublishTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).CreatePublishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_CreatePublishTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).CreatePublishTask(ctx, req.(*CreatePublishTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_ListPublishTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).ListPublishTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_ListPublishTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).ListPublishTasks(ctx, req.(*ListPublishTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_RetryPublishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryPublishTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).RetryPublishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_RetryPublishTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).RetryPublishTask(ctx, req.(*RetryPublishTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DispatchService_CancelPublishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPublishTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServiceServer).CancelPublishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchService_CancelPublishTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServiceServer).CancelPublishTask(ctx, req.(*CancelPublishTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchService_ServiceDesc is the grpc.ServiceDesc for DispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xsh.v1.DispatchService",
	HandlerType: (*DispatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlatformAccounts",
			Handler:    _DispatchService_ListPlatformAccounts_Handler,
		},
		{
			MethodName: "BindAccount",
			Handler:    _DispatchService_BindAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _DispatchService_UpdateAccount_Handler,
		},
		{
			MethodName: "UnbindAccount",
			Handler:    _DispatchService_UnbindAccount_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _DispatchService_ListSchedules_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _DispatchService_CreateSchedule_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _DispatchService_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _DispatchService_DeleteSchedule_Handler,
		},
		{
			MethodName: "CreatePublishTask",
			Handler:    _DispatchService_CreatePublishTask_Handler,
		},
		{
			MethodName: "ListPublishTasks",
			Handler:    _DispatchService_ListPublishTasks_Handler,
		},
		{
			MethodName: "RetryPublishTask",
			Handler:    _DispatchService_RetryPublishTask_Handler,
		},
		{
			MethodName: "CancelPublishTask",
			Handler:    _DispatchService_CancelPublishTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xsh/v1/dispatch.proto",
}
