// product.proto 定义选品采集仓（Input）模块的 API。
// 包含：链接解析、商品 CRUD、爆款榜单；首期不接淘宝联盟，支持手动录入与简单解析。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: xsh/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product 解析后的商品信息，对应表 xsh_products。
type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceUrl      string                 `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalPrice  float64                `protobuf:"fixed64,4,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CouponAmount   float64                `protobuf:"fixed64,5,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	CommissionRate float64                `protobuf:"fixed64,6,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsHot          bool                   `protobuf:"varint,8,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	RankSource     string                 `protobuf:"bytes,9,opt,name=rank_source,json=rankSource,proto3" json:"rank_source,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix 秒，与现有项目一致
	UpdatedAt      int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_xsh_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *Product) GetCouponAmount() float64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *Product) GetCommissionRate() float64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *Product) GetRankSource() string {
	if x != nil {
		return x.RankSource
	}
	return ""
}

func (x *Product) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Product) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ParseProductLink 请求：粘贴的淘宝/猫超等链接。
type ParseProductLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseProductLinkRequest) Reset() {
	*x = ParseProductLinkRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseProductLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseProductLinkRequest) ProtoMessage() {}

func (x *ParseProductLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseProductLinkRequest.ProtoReflect.Descriptor instead.
func (*ParseProductLinkRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ParseProductLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ParseProductLinkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseProductLinkReply) Reset() {
	*x = ParseProductLinkReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseProductLinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseProductLinkReply) ProtoMessage() {}

func (x *ParseProductLinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseProductLinkReply.ProtoReflect.Descriptor instead.
func (*ParseProductLinkReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *ParseProductLinkReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ParseProductLinkReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 从 1 起，默认 20
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IsHot         bool                   `protobuf:"varint,3,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"` // 为 true 时筛选神价
	RankSource    string                 `protobuf:"bytes,4,opt,name=rank_source,json=rankSource,proto3" json:"rank_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *ListProductsRequest) GetRankSource() string {
	if x != nil {
		return x.RankSource
	}
	return ""
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Product             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsReply) GetItems() []*Product {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// CreateProduct 用于手动录入商品（首期不依赖联盟 API）。
type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl      string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalPrice  float64                `protobuf:"fixed64,3,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CouponAmount   float64                `protobuf:"fixed64,4,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	CommissionRate float64                `protobuf:"fixed64,5,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsHot          bool                   `protobuf:"varint,7,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	RankSource     string                 `protobuf:"bytes,8,opt,name=rank_source,json=rankSource,proto3" json:"rank_source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *CreateProductRequest) GetCouponAmount() float64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *CreateProductRequest) GetCommissionRate() float64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

func (x *CreateProductRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateProductRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *CreateProductRequest) GetRankSource() string {
	if x != nil {
		return x.RankSource
	}
	return ""
}

type CreateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// UpdateProductRequest 仅需传 id，其余字段按需传递，非空则更新。
type UpdateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceUrl      string                 `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalPrice  float64                `protobuf:"fixed64,4,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	CouponAmount   float64                `protobuf:"fixed64,5,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	CommissionRate float64                `protobuf:"fixed64,6,opt,name=commission_rate,json=commissionRate,proto3" json:"commission_rate,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsHot          bool                   `protobuf:"varint,8,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	RankSource     string                 `protobuf:"bytes,9,opt,name=rank_source,json=rankSource,proto3" json:"rank_source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *UpdateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProductRequest) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetCouponAmount() float64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *UpdateProductRequest) GetCommissionRate() float64 {
	if x != nil {
		return x.CommissionRate
	}
	return 0
}

func (x *UpdateProductRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateProductRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *UpdateProductRequest) GetRankSource() string {
	if x != nil {
		return x.RankSource
	}
	return ""
}

type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReply) Reset() {
	*x = DeleteProductReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReply) ProtoMessage() {}

func (x *DeleteProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReply.ProtoReflect.Descriptor instead.
func (*DeleteProductReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// HotRank 爆款榜单快照，对应表 xsh_hot_ranks。
type HotRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RankType      string                 `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	SyncedAt      int64                  `protobuf:"varint,3,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	SnapshotJson  string                 `protobuf:"bytes,4,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"` // JSON 字符串
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotRank) Reset() {
	*x = HotRank{}
	mi := &file_xsh_v1_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRank) ProtoMessage() {}

func (x *HotRank) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRank.ProtoReflect.Descriptor instead.
func (*HotRank) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{13}
}

func (x *HotRank) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HotRank) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *HotRank) GetSyncedAt() int64 {
	if x != nil {
		return x.SyncedAt
	}
	return 0
}

func (x *HotRank) GetSnapshotJson() string {
	if x != nil {
		return x.SnapshotJson
	}
	return ""
}

func (x *HotRank) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListHotRanksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      string                 `protobuf:"bytes,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotRanksRequest) Reset() {
	*x = ListHotRanksRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotRanksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotRanksRequest) ProtoMessage() {}

func (x *ListHotRanksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotRanksRequest.ProtoReflect.Descriptor instead.
func (*ListHotRanksRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{14}
}

func (x *ListHotRanksRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *ListHotRanksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListHotRanksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListHotRanksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HotRank             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHotRanksReply) Reset() {
	*x = ListHotRanksReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHotRanksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotRanksReply) ProtoMessage() {}

func (x *ListHotRanksReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotRanksReply.ProtoReflect.Descriptor instead.
func (*ListHotRanksReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{15}
}

func (x *ListHotRanksReply) GetItems() []*HotRank {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListHotRanksReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SyncHotRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      string                 `protobuf:"bytes,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHotRankRequest) Reset() {
	*x = SyncHotRankRequest{}
	mi := &file_xsh_v1_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHotRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHotRankRequest) ProtoMessage() {}

func (x *SyncHotRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHotRankRequest.ProtoReflect.Descriptor instead.
func (*SyncHotRankRequest) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{16}
}

func (x *SyncHotRankRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

type SyncHotRankReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHotRankReply) Reset() {
	*x = SyncHotRankReply{}
	mi := &file_xsh_v1_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHotRankReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHotRankReply) ProtoMessage() {}

func (x *SyncHotRankReply) ProtoReflect() protoreflect.Message {
	mi := &file_xsh_v1_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHotRankReply.ProtoReflect.Descriptor instead.
func (*SyncHotRankReply) Descriptor() ([]byte, []int) {
	return file_xsh_v1_product_proto_rawDescGZIP(), []int{17}
}

func (x *SyncHotRankReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncHotRankReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_xsh_v1_product_proto protoreflect.FileDescriptor

const file_xsh_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x14xsh/v1/product.proto\x12\x06xsh.v1\x1a\x1cgoogle/api/annotations.proto\"\xd6\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_price\x18\x04 \x01(\x01R\roriginalPrice\x12#\n" +
	"\rcoupon_amount\x18\x05 \x01(\x01R\fcouponAmount\x12'\n" +
	"\x0fcommission_rate\x18\x06 \x01(\x01R\x0ecommissionRate\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x15\n" +
	"\x06is_hot\x18\b \x01(\bR\x05isHot\x12\x1f\n" +
	"\vrank_source\x18\t \x01(\tR\n" +
	"rankSource\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"+\n" +
	"\x17ParseProductLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"g\n" +
	"\x15ParseProductLinkReply\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.xsh.v1.ProductR\aproduct\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"~\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x15\n" +
	"\x06is_hot\x18\x03 \x01(\bR\x05isHot\x12\x1f\n" +
	"\vrank_source\x18\x04 \x01(\tR\n" +
	"rankSource\"P\n" +
	"\x11ListProductsReply\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.xsh.v1.ProductR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"<\n" +
	"\x0fGetProductReply\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.xsh.v1.ProductR\aproduct\"\x95\x02\n" +
	"\x14CreateProductRequest\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_price\x18\x03 \x01(\x01R\roriginalPrice\x12#\n" +
	"\rcoupon_amount\x18\x04 \x01(\x01R\fcouponAmount\x12'\n" +
	"\x0fcommission_rate\x18\x05 \x01(\x01R\x0ecommissionRate\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x15\n" +
	"\x06is_hot\x18\a \x01(\bR\x05isHot\x12\x1f\n" +
	"\vrank_source\x18\b \x01(\tR\n" +
	"rankSource\"?\n" +
	"\x12CreateProductReply\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.xsh.v1.ProductR\aproduct\"\xa5\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_price\x18\x04 \x01(\x01R\roriginalPrice\x12#\n" +
	"\rcoupon_amount\x18\x05 \x01(\x01R\fcouponAmount\x12'\n" +
	"\x0fcommission_rate\x18\x06 \x01(\x01R\x0ecommissionRate\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x15\n" +
	"\x06is_hot\x18\b \x01(\bR\x05isHot\x12\x1f\n" +
	"\vrank_source\x18\t \x01(\tR\n" +
	"rankSource\"?\n" +
	"\x12UpdateProductReply\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.xsh.v1.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\".\n" +
	"\x12DeleteProductReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x01\n" +
	"\aHotRank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x1b\n" +
	"\tsynced_at\x18\x03 \x01(\x03R\bsyncedAt\x12#\n" +
	"\rsnapshot_json\x18\x04 \x01(\tR\fsnapshotJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"c\n" +
	"\x13ListHotRanksRequest\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\tR\brankType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"P\n" +
	"\x11ListHotRanksReply\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.xsh.v1.HotRankR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"1\n" +
	"\x12SyncHotRankRequest\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\tR\brankType\"F\n" +
	"\x10SyncHotRankReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf4\x06\n" +
	"\x0eProductService\x12y\n" +
	"\x10ParseProductLink\x12\x1f.xsh.v1.ParseProductLinkRequest\x1a\x1d.xsh.v1.ParseProductLinkReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/xsh/v1/products/parse\x12d\n" +
	"\fListProducts\x12\x1b.xsh.v1.ListProductsRequest\x1a\x19.xsh.v1.ListProductsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/xsh/v1/products\x12c\n" +
	"\n" +
	"GetProduct\x12\x19.xsh.v1.GetProductRequest\x1a\x17.xsh.v1.GetProductReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/xsh/v1/products/{id}\x12j\n" +
	"\rCreateProduct\x12\x1c.xsh.v1.CreateProductRequest\x1a\x1a.xsh.v1.CreateProductReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/xsh/v1/products\x12o\n" +
	"\rUpdateProduct\x12\x1c.xsh.v1.UpdateProductRequest\x1a\x1a.xsh.v1.UpdateProductReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/xsh/v1/products/{id}\x12l\n" +
	"\rDeleteProduct\x12\x1c.xsh.v1.DeleteProductRequest\x1a\x1a.xsh.v1.DeleteProductReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/xsh/v1/products/{id}\x12e\n" +
	"\fListHotRanks\x12\x1b.xsh.v1.ListHotRanksRequest\x1a\x19.xsh.v1.ListHotRanksReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/xsh/v1/hot-ranks\x12j\n" +
	"\vSyncHotRank\x12\x1a.xsh.v1.SyncHotRankRequest\x1a\x18.xsh.v1.SyncHotRankReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/xsh/v1/hot-ranks/syncB\x19Z\x17realworld/api/xsh/v1;v1b\x06proto3"

var (
	file_xsh_v1_product_proto_rawDescOnce sync.Once
	file_xsh_v1_product_proto_rawDescData []byte
)

func file_xsh_v1_product_proto_rawDescGZIP() []byte {
	file_xsh_v1_product_proto_rawDescOnce.Do(func() {
		file_xsh_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xsh_v1_product_proto_rawDesc), len(file_xsh_v1_product_proto_rawDesc)))
	})
	return file_xsh_v1_product_proto_rawDescData
}

var file_xsh_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_xsh_v1_product_proto_goTypes = []any{
	(*Product)(nil),                 // 0: xsh.v1.Product
	(*ParseProductLinkRequest)(nil), // 1: xsh.v1.ParseProductLinkRequest
	(*ParseProductLinkReply)(nil),   // 2: xsh.v1.ParseProductLinkReply
	(*ListProductsRequest)(nil),     // 3: xsh.v1.ListProductsRequest
	(*ListProductsReply)(nil),       // 4: xsh.v1.ListProductsReply
	(*GetProductRequest)(nil),       // 5: xsh.v1.GetProductRequest
	(*GetProductReply)(nil),         // 6: xsh.v1.GetProductReply
	(*CreateProductRequest)(nil),    // 7: xsh.v1.CreateProductRequest
	(*CreateProductReply)(nil),      // 8: xsh.v1.CreateProductReply
	(*UpdateProductRequest)(nil),    // 9: xsh.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),      // 10: xsh.v1.UpdateProductReply
	(*DeleteProductRequest)(nil),    // 11: xsh.v1.DeleteProductRequest
	(*DeleteProductReply)(nil),      // 12: xsh.v1.DeleteProductReply
	(*HotRank)(nil),                 // 13: xsh.v1.HotRank
	(*ListHotRanksRequest)(nil),     // 14: xsh.v1.ListHotRanksRequest
	(*ListHotRanksReply)(nil),       // 15: xsh.v1.ListHotRanksReply
	(*SyncHotRankRequest)(nil),      // 16: xsh.v1.SyncHotRankRequest
	(*SyncHotRankReply)(nil),        // 17: xsh.v1.SyncHotRankReply
}
var file_xsh_v1_product_proto_depIdxs = []int32{
	0,  // 0: xsh.v1.ParseProductLinkReply.product:type_name -> xsh.v1.Product
	0,  // 1: xsh.v1.ListProductsReply.items:type_name -> xsh.v1.Product
	0,  // 2: xsh.v1.GetProductReply.product:type_name -> xsh.v1.Product
	0,  // 3: xsh.v1.CreateProductReply.product:type_name -> xsh.v1.Product
	0,  // 4: xsh.v1.UpdateProductReply.product:type_name -> xsh.v1.Product
	13, // 5: xsh.v1.ListHotRanksReply.items:type_name -> xsh.v1.HotRank
	1,  // 6: xsh.v1.ProductService.ParseProductLink:input_type -> xsh.v1.ParseProductLinkRequest
	3,  // 7: xsh.v1.ProductService.ListProducts:input_type -> xsh.v1.ListProductsRequest
	5,  // 8: xsh.v1.ProductService.GetProduct:input_type -> xsh.v1.GetProductRequest
	7,  // 9: xsh.v1.ProductService.CreateProduct:input_type -> xsh.v1.CreateProductRequest
	9,  // 10: xsh.v1.ProductService.UpdateProduct:input_type -> xsh.v1.UpdateProductRequest
	11, // 11: xsh.v1.ProductService.DeleteProduct:input_type -> xsh.v1.DeleteProductRequest
	14, // 12: xsh.v1.ProductService.ListHotRanks:input_type -> xsh.v1.ListHotRanksRequest
	16, // 13: xsh.v1.ProductService.SyncHotRank:input_type -> xsh.v1.SyncHotRankRequest
	2,  // 14: xsh.v1.ProductService.ParseProductLink:output_type -> xsh.v1.ParseProductLinkReply
	4,  // 15: xsh.v1.ProductService.ListProducts:output_type -> xsh.v1.ListProductsReply
	6,  // 16: xsh.v1.ProductService.GetProduct:output_type -> xsh.v1.GetProductReply
	8,  // 17: xsh.v1.ProductService.CreateProduct:output_type -> xsh.v1.CreateProductReply
	10, // 18: xsh.v1.ProductService.UpdateProduct:output_type -> xsh.v1.UpdateProductReply
	12, // 19: xsh.v1.ProductService.DeleteProduct:output_type -> xsh.v1.DeleteProductReply
	15, // 20: xsh.v1.ProductService.ListHotRanks:output_type -> xsh.v1.ListHotRanksReply
	17, // 21: xsh.v1.ProductService.SyncHotRank:output_type -> xsh.v1.SyncHotRankReply
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_xsh_v1_product_proto_init() }
func file_xsh_v1_product_proto_init() {
	if File_xsh_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xsh_v1_product_proto_rawDesc), len(file_xsh_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xsh_v1_product_proto_goTypes,
		DependencyIndexes: file_xsh_v1_product_proto_depIdxs,
		MessageInfos:      file_xsh_v1_product_proto_msgTypes,
	}.Build()
	File_xsh_v1_product_proto = out.File
	file_xsh_v1_product_proto_goTypes = nil
	file_xsh_v1_product_proto_depIdxs = nil
}
