// 萌宠之家（cat-admin）社交模块 API 定义
// 项目文档：docs-all/cat-admin/02-后端开发文档.md
// 好友列表、搜索用户、好友申请（发送/同意/拒绝）、排行榜

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: friend/v1/friend.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserBrief 用户简要信息（搜索、好友列表、排行榜共用）
type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	HeartPoints   int32                  `protobuf:"varint,6,opt,name=heart_points,proto3" json:"heart_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_friend_v1_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{0}
}

func (x *UserBrief) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBrief) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBrief) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserBrief) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserBrief) GetHeartPoints() int32 {
	if x != nil {
		return x.HeartPoints
	}
	return 0
}

// ListFriends 我的好友列表
type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{1}
}

type ListFriendsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*UserBrief           `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsReply) Reset() {
	*x = ListFriendsReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsReply) ProtoMessage() {}

func (x *ListFriendsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsReply.ProtoReflect.Descriptor instead.
func (*ListFriendsReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{2}
}

func (x *ListFriendsReply) GetFriends() []*UserBrief {
	if x != nil {
		return x.Friends
	}
	return nil
}

// SearchUsers 搜索用户，query: keyword
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserBrief           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersReply) Reset() {
	*x = SearchUsersReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReply) ProtoMessage() {}

func (x *SearchUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReply.ProtoReflect.Descriptor instead.
func (*SearchUsersReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUsersReply) GetUsers() []*UserBrief {
	if x != nil {
		return x.Users
	}
	return nil
}

// SendFriendRequest 发送好友申请
type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      uint64                 `protobuf:"varint,1,opt,name=to_user_id,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{5}
}

func (x *SendFriendRequestRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendFriendRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestReply) Reset() {
	*x = SendFriendRequestReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestReply) ProtoMessage() {}

func (x *SendFriendRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestReply.ProtoReflect.Descriptor instead.
func (*SendFriendRequestReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{6}
}

func (x *SendFriendRequestReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendFriendRequestReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FriendRequestItem 收到的好友申请项
type FriendRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,proto3" json:"from_user_id,omitempty"`
	FromUser      *UserBrief             `protobuf:"bytes,3,opt,name=from_user,proto3" json:"from_user,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestItem) Reset() {
	*x = FriendRequestItem{}
	mi := &file_friend_v1_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestItem) ProtoMessage() {}

func (x *FriendRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestItem.ProtoReflect.Descriptor instead.
func (*FriendRequestItem) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{7}
}

func (x *FriendRequestItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequestItem) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequestItem) GetFromUser() *UserBrief {
	if x != nil {
		return x.FromUser
	}
	return nil
}

func (x *FriendRequestItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequestItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendRequestItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListFriendRequests 收到的好友申请列表
type ListFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsRequest) Reset() {
	*x = ListFriendRequestsRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsRequest) ProtoMessage() {}

func (x *ListFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{8}
}

type ListFriendRequestsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestItem   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestsReply) Reset() {
	*x = ListFriendRequestsReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestsReply) ProtoMessage() {}

func (x *ListFriendRequestsReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestsReply.ProtoReflect.Descriptor instead.
func (*ListFriendRequestsReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{9}
}

func (x *ListFriendRequestsReply) GetRequests() []*FriendRequestItem {
	if x != nil {
		return x.Requests
	}
	return nil
}

// AcceptFriendRequest 同意申请，path: id 为申请 ID
type AcceptFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptFriendRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptFriendRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestReply) Reset() {
	*x = AcceptFriendRequestReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestReply) ProtoMessage() {}

func (x *AcceptFriendRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestReply.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptFriendRequestReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptFriendRequestReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RejectFriendRequest 拒绝申请
type RejectFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendRequestRequest) Reset() {
	*x = RejectFriendRequestRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequestRequest) ProtoMessage() {}

func (x *RejectFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{12}
}

func (x *RejectFriendRequestRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectFriendRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFriendRequestReply) Reset() {
	*x = RejectFriendRequestReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFriendRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequestReply) ProtoMessage() {}

func (x *RejectFriendRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequestReply.ProtoReflect.Descriptor instead.
func (*RejectFriendRequestReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{13}
}

func (x *RejectFriendRequestReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectFriendRequestReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetRanking 排行榜，query: type=heart_points|level, limit
type GetRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // heart_points / level
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingRequest) Reset() {
	*x = GetRankingRequest{}
	mi := &file_friend_v1_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingRequest) ProtoMessage() {}

func (x *GetRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingRequest.ProtoReflect.Descriptor instead.
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{14}
}

func (x *GetRankingRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRankingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranking       []*UserBrief           `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingReply) Reset() {
	*x = GetRankingReply{}
	mi := &file_friend_v1_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingReply) ProtoMessage() {}

func (x *GetRankingReply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_v1_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingReply.ProtoReflect.Descriptor instead.
func (*GetRankingReply) Descriptor() ([]byte, []int) {
	return file_friend_v1_friend_proto_rawDescGZIP(), []int{15}
}

func (x *GetRankingReply) GetRanking() []*UserBrief {
	if x != nil {
		return x.Ranking
	}
	return nil
}

var File_friend_v1_friend_proto protoreflect.FileDescriptor

const file_friend_v1_friend_proto_rawDesc = "" +
	"\n" +
	"\x16friend/v1/friend.proto\x12\tfriend.v1\x1a\x1cgoogle/api/annotations.proto\"\xad\x01\n" +
	"\tUserBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1e\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\n" +
	"avatar_url\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\"\n" +
	"\fheart_points\x18\x06 \x01(\x05R\fheart_points\"\x14\n" +
	"\x12ListFriendsRequest\"B\n" +
	"\x10ListFriendsReply\x12.\n" +
	"\afriends\x18\x01 \x03(\v2\x14.friend.v1.UserBriefR\afriends\".\n" +
	"\x12SearchUsersRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\">\n" +
	"\x10SearchUsersReply\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.friend.v1.UserBriefR\x05users\"T\n" +
	"\x18SendFriendRequestRequest\x12\x1e\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\x04R\n" +
	"to_user_id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x16SendFriendRequestReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x01\n" +
	"\x11FriendRequestItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\ffrom_user_id\x122\n" +
	"\tfrom_user\x18\x03 \x01(\v2\x14.friend.v1.UserBriefR\tfrom_user\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\n" +
	"created_at\"\x1b\n" +
	"\x19ListFriendRequestsRequest\"S\n" +
	"\x17ListFriendRequestsReply\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.friend.v1.FriendRequestItemR\brequests\",\n" +
	"\x1aAcceptFriendRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"N\n" +
	"\x18AcceptFriendRequestReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x1aRejectFriendRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"N\n" +
	"\x18RejectFriendRequestReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x11GetRankingRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"A\n" +
	"\x0fGetRankingReply\x12.\n" +
	"\aranking\x18\x01 \x03(\v2\x14.friend.v1.UserBriefR\aranking2\xed\x06\n" +
	"\rFriendService\x12b\n" +
	"\vListFriends\x12\x1d.friend.v1.ListFriendsRequest\x1a\x1b.friend.v1.ListFriendsReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/friends\x12i\n" +
	"\vSearchUsers\x12\x1d.friend.v1.SearchUsersRequest\x1a\x1b.friend.v1.SearchUsersReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/friends/search\x12\x7f\n" +
	"\x11SendFriendRequest\x12#.friend.v1.SendFriendRequestRequest\x1a!.friend.v1.SendFriendRequestReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/friends/request\x12\x80\x01\n" +
	"\x12ListFriendRequests\x12$.friend.v1.ListFriendRequestsRequest\x1a\".friend.v1.ListFriendRequestsReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/friends/requests\x12\x92\x01\n" +
	"\x13AcceptFriendRequest\x12%.friend.v1.AcceptFriendRequestRequest\x1a#.friend.v1.AcceptFriendRequestReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/friends/requests/{id}/accept\x12\x92\x01\n" +
	"\x13RejectFriendRequest\x12%.friend.v1.RejectFriendRequestRequest\x1a#.friend.v1.RejectFriendRequestReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/friends/requests/{id}/reject\x12_\n" +
	"\n" +
	"GetRanking\x12\x1c.friend.v1.GetRankingRequest\x1a\x1a.friend.v1.GetRankingReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/rankingB\x1cZ\x1arealworld/api/friend/v1;v1b\x06proto3"

var (
	file_friend_v1_friend_proto_rawDescOnce sync.Once
	file_friend_v1_friend_proto_rawDescData []byte
)

func file_friend_v1_friend_proto_rawDescGZIP() []byte {
	file_friend_v1_friend_proto_rawDescOnce.Do(func() {
		file_friend_v1_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_v1_friend_proto_rawDesc), len(file_friend_v1_friend_proto_rawDesc)))
	})
	return file_friend_v1_friend_proto_rawDescData
}

var file_friend_v1_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_friend_v1_friend_proto_goTypes = []any{
	(*UserBrief)(nil),                  // 0: friend.v1.UserBrief
	(*ListFriendsRequest)(nil),         // 1: friend.v1.ListFriendsRequest
	(*ListFriendsReply)(nil),           // 2: friend.v1.ListFriendsReply
	(*SearchUsersRequest)(nil),         // 3: friend.v1.SearchUsersRequest
	(*SearchUsersReply)(nil),           // 4: friend.v1.SearchUsersReply
	(*SendFriendRequestRequest)(nil),   // 5: friend.v1.SendFriendRequestRequest
	(*SendFriendRequestReply)(nil),     // 6: friend.v1.SendFriendRequestReply
	(*FriendRequestItem)(nil),          // 7: friend.v1.FriendRequestItem
	(*ListFriendRequestsRequest)(nil),  // 8: friend.v1.ListFriendRequestsRequest
	(*ListFriendRequestsReply)(nil),    // 9: friend.v1.ListFriendRequestsReply
	(*AcceptFriendRequestRequest)(nil), // 10: friend.v1.AcceptFriendRequestRequest
	(*AcceptFriendRequestReply)(nil),   // 11: friend.v1.AcceptFriendRequestReply
	(*RejectFriendRequestRequest)(nil), // 12: friend.v1.RejectFriendRequestRequest
	(*RejectFriendRequestReply)(nil),   // 13: friend.v1.RejectFriendRequestReply
	(*GetRankingRequest)(nil),          // 14: friend.v1.GetRankingRequest
	(*GetRankingReply)(nil),            // 15: friend.v1.GetRankingReply
}
var file_friend_v1_friend_proto_depIdxs = []int32{
	0,  // 0: friend.v1.ListFriendsReply.friends:type_name -> friend.v1.UserBrief
	0,  // 1: friend.v1.SearchUsersReply.users:type_name -> friend.v1.UserBrief
	0,  // 2: friend.v1.FriendRequestItem.from_user:type_name -> friend.v1.UserBrief
	7,  // 3: friend.v1.ListFriendRequestsReply.requests:type_name -> friend.v1.FriendRequestItem
	0,  // 4: friend.v1.GetRankingReply.ranking:type_name -> friend.v1.UserBrief
	1,  // 5: friend.v1.FriendService.ListFriends:input_type -> friend.v1.ListFriendsRequest
	3,  // 6: friend.v1.FriendService.SearchUsers:input_type -> friend.v1.SearchUsersRequest
	5,  // 7: friend.v1.FriendService.SendFriendRequest:input_type -> friend.v1.SendFriendRequestRequest
	8,  // 8: friend.v1.FriendService.ListFriendRequests:input_type -> friend.v1.ListFriendRequestsRequest
	10, // 9: friend.v1.FriendService.AcceptFriendRequest:input_type -> friend.v1.AcceptFriendRequestRequest
	12, // 10: friend.v1.FriendService.RejectFriendRequest:input_type -> friend.v1.RejectFriendRequestRequest
	14, // 11: friend.v1.FriendService.GetRanking:input_type -> friend.v1.GetRankingRequest
	2,  // 12: friend.v1.FriendService.ListFriends:output_type -> friend.v1.ListFriendsReply
	4,  // 13: friend.v1.FriendService.SearchUsers:output_type -> friend.v1.SearchUsersReply
	6,  // 14: friend.v1.FriendService.SendFriendRequest:output_type -> friend.v1.SendFriendRequestReply
	9,  // 15: friend.v1.FriendService.ListFriendRequests:output_type -> friend.v1.ListFriendRequestsReply
	11, // 16: friend.v1.FriendService.AcceptFriendRequest:output_type -> friend.v1.AcceptFriendRequestReply
	13, // 17: friend.v1.FriendService.RejectFriendRequest:output_type -> friend.v1.RejectFriendRequestReply
	15, // 18: friend.v1.FriendService.GetRanking:output_type -> friend.v1.GetRankingReply
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_friend_v1_friend_proto_init() }
func file_friend_v1_friend_proto_init() {
	if File_friend_v1_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_v1_friend_proto_rawDesc), len(file_friend_v1_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_v1_friend_proto_goTypes,
		DependencyIndexes: file_friend_v1_friend_proto_depIdxs,
		MessageInfos:      file_friend_v1_friend_proto_msgTypes,
	}.Build()
	File_friend_v1_friend_proto = out.File
	file_friend_v1_friend_proto_goTypes = nil
	file_friend_v1_friend_proto_depIdxs = nil
}
