// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/verifyCOde/verifyCode.proto

package verifyCode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 验证码类型
type TYPE int32

const (
	TYPE_DEFAULT         TYPE = 0
	TYPE_REGISTER        TYPE = 1
	TYPE_LOGIN           TYPE = 2
	TYPE_CHANGE_PASSWORD TYPE = 3
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "DEFAULT",
		1: "REGISTER",
		2: "LOGIN",
		3: "CHANGE_PASSWORD",
	}
	TYPE_value = map[string]int32{
		"DEFAULT":         0,
		"REGISTER":        1,
		"LOGIN":           2,
		"CHANGE_PASSWORD": 3,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_verifyCOde_verifyCode_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_api_verifyCOde_verifyCode_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{0}
}

type CreateVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVerifyCodeRequest) Reset() {
	*x = CreateVerifyCodeRequest{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeRequest) ProtoMessage() {}

func (x *CreateVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{0}
}

type CreateVerifyCodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVerifyCodeReply) Reset() {
	*x = CreateVerifyCodeReply{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeReply) ProtoMessage() {}

func (x *CreateVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{1}
}

type UpdateVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVerifyCodeRequest) Reset() {
	*x = UpdateVerifyCodeRequest{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyCodeRequest) ProtoMessage() {}

func (x *UpdateVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{2}
}

type UpdateVerifyCodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVerifyCodeReply) Reset() {
	*x = UpdateVerifyCodeReply{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyCodeReply) ProtoMessage() {}

func (x *UpdateVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*UpdateVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{3}
}

type DeleteVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVerifyCodeRequest) Reset() {
	*x = DeleteVerifyCodeRequest{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVerifyCodeRequest) ProtoMessage() {}

func (x *DeleteVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{4}
}

type DeleteVerifyCodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVerifyCodeReply) Reset() {
	*x = DeleteVerifyCodeReply{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVerifyCodeReply) ProtoMessage() {}

func (x *DeleteVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*DeleteVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{5}
}

type GetVerifyCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码长度
	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// 验证码类型
	Type          TYPE `protobuf:"varint,2,opt,name=type,proto3,enum=api.verifyCode.TYPE" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeRequest) Reset() {
	*x = GetVerifyCodeRequest{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRequest) ProtoMessage() {}

func (x *GetVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{6}
}

func (x *GetVerifyCodeRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetVerifyCodeRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_DEFAULT
}

type GetVerifyCodeReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生成验证码
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReply) Reset() {
	*x = GetVerifyCodeReply{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply) ProtoMessage() {}

func (x *GetVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{7}
}

func (x *GetVerifyCodeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerifyCodeRequest) Reset() {
	*x = ListVerifyCodeRequest{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifyCodeRequest) ProtoMessage() {}

func (x *ListVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*ListVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{8}
}

type ListVerifyCodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerifyCodeReply) Reset() {
	*x = ListVerifyCodeReply{}
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifyCodeReply) ProtoMessage() {}

func (x *ListVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verifyCOde_verifyCode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*ListVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verifyCOde_verifyCode_proto_rawDescGZIP(), []int{9}
}

var File_api_verifyCOde_verifyCode_proto protoreflect.FileDescriptor

const file_api_verifyCOde_verifyCode_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/verifyCOde/verifyCode.proto\x12\x0eapi.verifyCode\"\x19\n" +
	"\x17CreateVerifyCodeRequest\"\x17\n" +
	"\x15CreateVerifyCodeReply\"\x19\n" +
	"\x17UpdateVerifyCodeRequest\"\x17\n" +
	"\x15UpdateVerifyCodeReply\"\x19\n" +
	"\x17DeleteVerifyCodeRequest\"\x17\n" +
	"\x15DeleteVerifyCodeReply\"X\n" +
	"\x14GetVerifyCodeRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.api.verifyCode.TYPER\x04type\"(\n" +
	"\x12GetVerifyCodeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x17\n" +
	"\x15ListVerifyCodeRequest\"\x15\n" +
	"\x13ListVerifyCodeReply*A\n" +
	"\x04TYPE\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\t\n" +
	"\x05LOGIN\x10\x02\x12\x13\n" +
	"\x0fCHANGE_PASSWORD\x10\x032\xf1\x03\n" +
	"\n" +
	"VerifyCode\x12b\n" +
	"\x10CreateVerifyCode\x12'.api.verifyCode.CreateVerifyCodeRequest\x1a%.api.verifyCode.CreateVerifyCodeReply\x12b\n" +
	"\x10UpdateVerifyCode\x12'.api.verifyCode.UpdateVerifyCodeRequest\x1a%.api.verifyCode.UpdateVerifyCodeReply\x12b\n" +
	"\x10DeleteVerifyCode\x12'.api.verifyCode.DeleteVerifyCodeRequest\x1a%.api.verifyCode.DeleteVerifyCodeReply\x12Y\n" +
	"\rGetVerifyCode\x12$.api.verifyCode.GetVerifyCodeRequest\x1a\".api.verifyCode.GetVerifyCodeReply\x12\\\n" +
	"\x0eListVerifyCode\x12%.api.verifyCode.ListVerifyCodeRequest\x1a#.api.verifyCode.ListVerifyCodeReplyB8\n" +
	"\x0eapi.verifyCodeP\x01Z$verifyCode/api/verifyCode;verifyCodeb\x06proto3"

var (
	file_api_verifyCOde_verifyCode_proto_rawDescOnce sync.Once
	file_api_verifyCOde_verifyCode_proto_rawDescData []byte
)

func file_api_verifyCOde_verifyCode_proto_rawDescGZIP() []byte {
	file_api_verifyCOde_verifyCode_proto_rawDescOnce.Do(func() {
		file_api_verifyCOde_verifyCode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_verifyCOde_verifyCode_proto_rawDesc), len(file_api_verifyCOde_verifyCode_proto_rawDesc)))
	})
	return file_api_verifyCOde_verifyCode_proto_rawDescData
}

var file_api_verifyCOde_verifyCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_verifyCOde_verifyCode_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_verifyCOde_verifyCode_proto_goTypes = []any{
	(TYPE)(0),                       // 0: api.verifyCode.TYPE
	(*CreateVerifyCodeRequest)(nil), // 1: api.verifyCode.CreateVerifyCodeRequest
	(*CreateVerifyCodeReply)(nil),   // 2: api.verifyCode.CreateVerifyCodeReply
	(*UpdateVerifyCodeRequest)(nil), // 3: api.verifyCode.UpdateVerifyCodeRequest
	(*UpdateVerifyCodeReply)(nil),   // 4: api.verifyCode.UpdateVerifyCodeReply
	(*DeleteVerifyCodeRequest)(nil), // 5: api.verifyCode.DeleteVerifyCodeRequest
	(*DeleteVerifyCodeReply)(nil),   // 6: api.verifyCode.DeleteVerifyCodeReply
	(*GetVerifyCodeRequest)(nil),    // 7: api.verifyCode.GetVerifyCodeRequest
	(*GetVerifyCodeReply)(nil),      // 8: api.verifyCode.GetVerifyCodeReply
	(*ListVerifyCodeRequest)(nil),   // 9: api.verifyCode.ListVerifyCodeRequest
	(*ListVerifyCodeReply)(nil),     // 10: api.verifyCode.ListVerifyCodeReply
}
var file_api_verifyCOde_verifyCode_proto_depIdxs = []int32{
	0,  // 0: api.verifyCode.GetVerifyCodeRequest.type:type_name -> api.verifyCode.TYPE
	1,  // 1: api.verifyCode.VerifyCode.CreateVerifyCode:input_type -> api.verifyCode.CreateVerifyCodeRequest
	3,  // 2: api.verifyCode.VerifyCode.UpdateVerifyCode:input_type -> api.verifyCode.UpdateVerifyCodeRequest
	5,  // 3: api.verifyCode.VerifyCode.DeleteVerifyCode:input_type -> api.verifyCode.DeleteVerifyCodeRequest
	7,  // 4: api.verifyCode.VerifyCode.GetVerifyCode:input_type -> api.verifyCode.GetVerifyCodeRequest
	9,  // 5: api.verifyCode.VerifyCode.ListVerifyCode:input_type -> api.verifyCode.ListVerifyCodeRequest
	2,  // 6: api.verifyCode.VerifyCode.CreateVerifyCode:output_type -> api.verifyCode.CreateVerifyCodeReply
	4,  // 7: api.verifyCode.VerifyCode.UpdateVerifyCode:output_type -> api.verifyCode.UpdateVerifyCodeReply
	6,  // 8: api.verifyCode.VerifyCode.DeleteVerifyCode:output_type -> api.verifyCode.DeleteVerifyCodeReply
	8,  // 9: api.verifyCode.VerifyCode.GetVerifyCode:output_type -> api.verifyCode.GetVerifyCodeReply
	10, // 10: api.verifyCode.VerifyCode.ListVerifyCode:output_type -> api.verifyCode.ListVerifyCodeReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_verifyCOde_verifyCode_proto_init() }
func file_api_verifyCOde_verifyCode_proto_init() {
	if File_api_verifyCOde_verifyCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_verifyCOde_verifyCode_proto_rawDesc), len(file_api_verifyCOde_verifyCode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_verifyCOde_verifyCode_proto_goTypes,
		DependencyIndexes: file_api_verifyCOde_verifyCode_proto_depIdxs,
		EnumInfos:         file_api_verifyCOde_verifyCode_proto_enumTypes,
		MessageInfos:      file_api_verifyCOde_verifyCode_proto_msgTypes,
	}.Build()
	File_api_verifyCOde_verifyCode_proto = out.File
	file_api_verifyCOde_verifyCode_proto_goTypes = nil
	file_api_verifyCOde_verifyCode_proto_depIdxs = nil
}
